// Generated by bpmn-to-code
@file:Suppress("unused")

package io.miragon.blueprint.adapter.process

import io.miragon.bpmn.runtime.AbstractFlowNode
import io.miragon.bpmn.runtime.AssociatedCompensationHandler
import io.miragon.bpmn.runtime.AttachedBoundaryEvent
import io.miragon.bpmn.runtime.BoundaryEvent
import io.miragon.bpmn.runtime.BpmnElementType
import io.miragon.bpmn.runtime.BpmnEngine
import io.miragon.bpmn.runtime.BpmnErrorDefinition
import io.miragon.bpmn.runtime.BpmnEscalationDefinition
import io.miragon.bpmn.runtime.BpmnEventType
import io.miragon.bpmn.runtime.BpmnTimer
import io.miragon.bpmn.runtime.CallActivity
import io.miragon.bpmn.runtime.CompensationThrowEvent
import io.miragon.bpmn.runtime.ElementId
import io.miragon.bpmn.runtime.ErrorEvent
import io.miragon.bpmn.runtime.EscalationEvent
import io.miragon.bpmn.runtime.Event
import io.miragon.bpmn.runtime.FlowNode
import io.miragon.bpmn.runtime.FlowScope
import io.miragon.bpmn.runtime.HasJobType
import io.miragon.bpmn.runtime.HasMessage
import io.miragon.bpmn.runtime.HasSuccessors
import io.miragon.bpmn.runtime.HasVariables
import io.miragon.bpmn.runtime.InputOutputMapping
import io.miragon.bpmn.runtime.MessageName
import io.miragon.bpmn.runtime.ProcessId
import io.miragon.bpmn.runtime.RegisteredVariableDefinitions
import io.miragon.bpmn.runtime.SequenceFlows
import io.miragon.bpmn.runtime.TimerEvent
import io.miragon.bpmn.runtime.TimerType
import io.miragon.bpmn.runtime.VariableName
import kotlin.Boolean
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

object BikeLeasingProcessProcessApi {
  val PROCESS_ID: ProcessId = ProcessId("bikeLeasingProcess")

  val PROCESS_ENGINE: BpmnEngine = BpmnEngine.ZEEBE

  /**
   * Typed navigation over the process flow: one nested object per BPMN element.
   */
  object FlowNodes {
    val all: List<FlowNode> = listOf(
      BusinessRuleTaskCheckCreditRating,
      CallActivityCancelBikeOrder,
      EndEventApplicationCancelled,
      EndEventApplicationRejected,
      EndEventContractCancelled,
      EndEventContractValid,
      EndEventLeasingActive,
      EndEventNotSigned,
      EndEventProspectReminded,
      EventBikeUnavailable,
      EventCompensateContract,
      EventCompensateInsurance,
      EventCompensateOrder,
      EventContractNotSigned,
      EventContractSigned,
      EventHandoverReported,
      EventReverseApplication,
      EventSignatureDeadline,
      EventSignatureReminder,
      EventTriggerReversal,
      EventWithdrawalPeriodElapsed,
      GatewayAlternativeFound,
      GatewayAwaitSignature,
      GatewayBikeSourceJoin,
      GatewayFork,
      GatewayIsSolvent,
      GatewayJoin,
      GatewayRejectionJoin,
      ServiceTaskActivateLeasing,
      ServiceTaskCancelContract,
      ServiceTaskCancelPolicy,
      ServiceTaskConfirmContractCancellation,
      ServiceTaskIssueInsurancePolicy,
      ServiceTaskOrderBike,
      ServiceTaskSendCancellationConfirmation,
      ServiceTaskSendContract,
      ServiceTaskSendRejection,
      ServiceTaskSendReminderMail,
      StartEventApplicationWithdrawn,
      StartEventCustomerEligible,
      StartEventLeasingRequestReceived,
      SubProcessApplicationWithdrawn,
      SubProcessConcludeContract,
      UserTaskClarifyAlternative,
    )

    object BusinessRuleTaskCheckCreditRating : AbstractFlowNode(
      id = ElementId(BusinessRuleTaskCheckCreditRating.ELEMENT_ID),
      elementType = BpmnElementType.BUSINESS_RULE_TASK,
      name = "Check credit rating",
    ), HasSuccessors<BusinessRuleTaskCheckCreditRating.Next> {
      const val ELEMENT_ID: String = "businessRuleTask_checkCreditRating"

      override val next: Next = Next

      object Next {
        val gatewayIsSolvent: SequenceFlows<GatewayIsSolvent>
          get() = SequenceFlows.single(
            flowId = ElementId("flow_checkCreditToSolvent"),
            target = GatewayIsSolvent,
          )
      }
    }

    object CallActivityCancelBikeOrder : AbstractFlowNode(
      id = ElementId(CallActivityCancelBikeOrder.ELEMENT_ID),
      elementType = BpmnElementType.CALL_ACTIVITY,
      name = "Cancel bike order",
    ), CallActivity, HasVariables {
      const val ELEMENT_ID: String = "callActivity_cancelBikeOrder"

      override val calledProcess: ProcessId = ProcessId("cancelBikeOrder")

      override val variables: Variables = Variables

      object Variables : RegisteredVariableDefinitions() {
        val APPLICATION_ID: VariableName.Input = input(ProcessVariables.APPLICATION_ID)

        val BIKE_ID: VariableName.Input = input(ProcessVariables.BIKE_ID)

        val ORDER_ID: VariableName.Input = input(ProcessVariables.ORDER_ID)
      }

      object Inputs {
        val APPLICATION_ID: InputOutputMapping = InputOutputMapping(
          target = "applicationId",
          source = "=applicationId",
        )

        val BIKE_ID: InputOutputMapping = InputOutputMapping(
          target = "bikeId",
          source = "=bikeId",
        )

        val ORDER_ID: InputOutputMapping = InputOutputMapping(
          target = "orderId",
          source = "=orderId",
        )
      }
    }

    object EndEventApplicationCancelled : AbstractFlowNode(
      id = ElementId(EndEventApplicationCancelled.ELEMENT_ID),
      elementType = BpmnElementType.END_EVENT,
      name = "Leasing cancelled",
    ), Event {
      override val eventType: BpmnEventType = BpmnEventType.NONE

      const val ELEMENT_ID: String = "endEvent_applicationCancelled"
    }

    object EndEventApplicationRejected : AbstractFlowNode(
      id = ElementId(EndEventApplicationRejected.ELEMENT_ID),
      elementType = BpmnElementType.END_EVENT,
      name = "Application rejected",
    ), Event {
      override val eventType: BpmnEventType = BpmnEventType.NONE

      const val ELEMENT_ID: String = "endEvent_applicationRejected"
    }

    object EndEventContractCancelled : AbstractFlowNode(
      id = ElementId(EndEventContractCancelled.ELEMENT_ID),
      elementType = BpmnElementType.END_EVENT,
      name = "Contract cancelled",
    ), Event {
      override val eventType: BpmnEventType = BpmnEventType.TERMINATE

      const val ELEMENT_ID: String = "endEvent_contractCancelled"
    }

    object EndEventContractValid : AbstractFlowNode(
      id = ElementId(EndEventContractValid.ELEMENT_ID),
      elementType = BpmnElementType.END_EVENT,
      name = "Contract valid",
    ), Event {
      override val eventType: BpmnEventType = BpmnEventType.NONE

      const val ELEMENT_ID: String = "endEvent_contractValid"
    }

    object EndEventLeasingActive : AbstractFlowNode(
      id = ElementId(EndEventLeasingActive.ELEMENT_ID),
      elementType = BpmnElementType.END_EVENT,
      name = "Leasing active",
    ), Event {
      override val eventType: BpmnEventType = BpmnEventType.NONE

      const val ELEMENT_ID: String = "endEvent_leasingActive"
    }

    object EndEventNotSigned : AbstractFlowNode(
      id = ElementId(EndEventNotSigned.ELEMENT_ID),
      elementType = BpmnElementType.END_EVENT,
      name = "Not signed",
    ), Event, EscalationEvent {
      override val eventType: BpmnEventType = BpmnEventType.ESCALATION

      const val ELEMENT_ID: String = "endEvent_notSigned"

      override val escalation: BpmnEscalationDefinition = Escalations.CONTRACT_NOT_SIGNED
    }

    object EndEventProspectReminded : AbstractFlowNode(
      id = ElementId(EndEventProspectReminded.ELEMENT_ID),
      elementType = BpmnElementType.END_EVENT,
      name = "Prospect reminded",
    ), Event {
      override val eventType: BpmnEventType = BpmnEventType.NONE

      const val ELEMENT_ID: String = "endEvent_prospectReminded"
    }

    object EventBikeUnavailable : AbstractFlowNode(
      id = ElementId(EventBikeUnavailable.ELEMENT_ID),
      elementType = BpmnElementType.BOUNDARY_EVENT,
      name = "Bike unavailable",
    ), HasSuccessors<EventBikeUnavailable.Next>, BoundaryEvent<ServiceTaskOrderBike>, ErrorEvent {
      override val eventType: BpmnEventType = BpmnEventType.ERROR

      const val ELEMENT_ID: String = "event_bikeUnavailable"

      override val error: BpmnErrorDefinition = Errors.BIKE_UNAVAILABLE

      override val attachedTo: ServiceTaskOrderBike
        get() = ServiceTaskOrderBike

      override val isInterrupting: Boolean = true

      override val next: Next = Next

      object Next {
        val userTaskClarifyAlternative: SequenceFlows<UserTaskClarifyAlternative>
          get() = SequenceFlows.single(
            flowId = ElementId("flow_bikeUnavailableToClarify"),
            target = UserTaskClarifyAlternative,
          )
      }
    }

    object EventCompensateContract : AbstractFlowNode(
      id = ElementId(EventCompensateContract.ELEMENT_ID),
      elementType = BpmnElementType.BOUNDARY_EVENT,
      name = "Compensate contract",
    ), HasSuccessors<EventCompensateContract.Next>, BoundaryEvent<SubProcessConcludeContract> {
      override val eventType: BpmnEventType = BpmnEventType.COMPENSATION

      const val ELEMENT_ID: String = "event_compensateContract"

      override val attachedTo: SubProcessConcludeContract
        get() = SubProcessConcludeContract

      override val isInterrupting: Boolean = true

      override val next: Next = Next

      object Next {
        val serviceTaskCancelContract:
            AssociatedCompensationHandler<ServiceTaskCancelContract>
          get() = AssociatedCompensationHandler(target = ServiceTaskCancelContract)
      }
    }

    object EventCompensateInsurance : AbstractFlowNode(
      id = ElementId(EventCompensateInsurance.ELEMENT_ID),
      elementType = BpmnElementType.BOUNDARY_EVENT,
      name = "Compensate policy",
    ), HasSuccessors<EventCompensateInsurance.Next>,
        BoundaryEvent<ServiceTaskIssueInsurancePolicy> {
      override val eventType: BpmnEventType = BpmnEventType.COMPENSATION

      const val ELEMENT_ID: String = "event_compensateInsurance"

      override val attachedTo: ServiceTaskIssueInsurancePolicy
        get() = ServiceTaskIssueInsurancePolicy

      override val isInterrupting: Boolean = true

      override val next: Next = Next

      object Next {
        val serviceTaskCancelPolicy: AssociatedCompensationHandler<ServiceTaskCancelPolicy>
          get() = AssociatedCompensationHandler(target = ServiceTaskCancelPolicy)
      }
    }

    object EventCompensateOrder : AbstractFlowNode(
      id = ElementId(EventCompensateOrder.ELEMENT_ID),
      elementType = BpmnElementType.BOUNDARY_EVENT,
      name = "Compensate order",
    ), HasSuccessors<EventCompensateOrder.Next>, BoundaryEvent<ServiceTaskOrderBike> {
      override val eventType: BpmnEventType = BpmnEventType.COMPENSATION

      const val ELEMENT_ID: String = "event_compensateOrder"

      override val attachedTo: ServiceTaskOrderBike
        get() = ServiceTaskOrderBike

      override val isInterrupting: Boolean = true

      override val next: Next = Next

      object Next {
        val callActivityCancelBikeOrder:
            AssociatedCompensationHandler<CallActivityCancelBikeOrder>
          get() = AssociatedCompensationHandler(target = CallActivityCancelBikeOrder)
      }
    }

    object EventContractNotSigned : AbstractFlowNode(
      id = ElementId(EventContractNotSigned.ELEMENT_ID),
      elementType = BpmnElementType.BOUNDARY_EVENT,
      name = "Contract not signed",
    ), HasSuccessors<EventContractNotSigned.Next>, BoundaryEvent<SubProcessConcludeContract>,
        EscalationEvent {
      override val eventType: BpmnEventType = BpmnEventType.ESCALATION

      const val ELEMENT_ID: String = "event_contractNotSigned"

      override val escalation: BpmnEscalationDefinition = Escalations.CONTRACT_NOT_SIGNED

      override val attachedTo: SubProcessConcludeContract
        get() = SubProcessConcludeContract

      override val isInterrupting: Boolean = true

      override val next: Next = Next

      object Next {
        val gatewayRejectionJoin: SequenceFlows<GatewayRejectionJoin>
          get() = SequenceFlows.single(
            flowId = ElementId("flow_notSignedToRejectionJoin"),
            target = GatewayRejectionJoin,
          )
      }
    }

    object EventContractSigned : AbstractFlowNode(
      id = ElementId(EventContractSigned.ELEMENT_ID),
      elementType = BpmnElementType.INTERMEDIATE_CATCH_EVENT,
      name = "Contract signed",
    ), HasSuccessors<EventContractSigned.Next>, Event, HasMessage {
      override val eventType: BpmnEventType = BpmnEventType.MESSAGE

      const val ELEMENT_ID: String = "event_contractSigned"

      override val message: MessageName = Messages.MIRAVELO_CONTRACT_SIGNED

      override val next: Next = Next

      object Next {
        val endEventContractValid: SequenceFlows<EndEventContractValid>
          get() = SequenceFlows.single(
            flowId = ElementId("flow_contractSignedToValid"),
            target = EndEventContractValid,
          )
      }
    }

    object EventHandoverReported : AbstractFlowNode(
      id = ElementId(EventHandoverReported.ELEMENT_ID),
      elementType = BpmnElementType.INTERMEDIATE_CATCH_EVENT,
      name = "Handover reported",
    ), HasSuccessors<EventHandoverReported.Next>, Event, HasMessage {
      override val eventType: BpmnEventType = BpmnEventType.MESSAGE

      const val ELEMENT_ID: String = "event_handoverReported"

      override val message: MessageName = Messages.MIRAVELO_HANDOVER_REPORTED

      override val next: Next = Next

      object Next {
        val eventWithdrawalPeriodElapsed: SequenceFlows<EventWithdrawalPeriodElapsed>
          get() = SequenceFlows.single(
            flowId = ElementId("flow_handoverToWithdrawalPeriod"),
            target = EventWithdrawalPeriodElapsed,
          )
      }
    }

    object EventReverseApplication : AbstractFlowNode(
      id = ElementId(EventReverseApplication.ELEMENT_ID),
      elementType = BpmnElementType.INTERMEDIATE_THROW_EVENT,
      name = "Reverse application",
    ), HasSuccessors<EventReverseApplication.Next>, Event, CompensationThrowEvent {
      override val eventType: BpmnEventType = BpmnEventType.COMPENSATION

      const val ELEMENT_ID: String = "event_reverseApplication"

      override val next: Next = Next

      object Next {
        val serviceTaskSendCancellationConfirmation:
            SequenceFlows<ServiceTaskSendCancellationConfirmation>
          get() = SequenceFlows.single(
            flowId = ElementId("flow_reverseToSendConfirmation"),
            target = ServiceTaskSendCancellationConfirmation,
          )
      }
    }

    object EventSignatureDeadline : AbstractFlowNode(
      id = ElementId(EventSignatureDeadline.ELEMENT_ID),
      elementType = BpmnElementType.INTERMEDIATE_CATCH_EVENT,
      name = "14 days",
    ), HasSuccessors<EventSignatureDeadline.Next>, Event, TimerEvent {
      override val eventType: BpmnEventType = BpmnEventType.TIMER

      const val ELEMENT_ID: String = "event_signatureDeadline"

      override val timer: BpmnTimer = BpmnTimer(
        type = TimerType.DURATION,
        timerValue = "P14D",
      )

      override val next: Next = Next

      object Next {
        val endEventNotSigned: SequenceFlows<EndEventNotSigned>
          get() = SequenceFlows.single(
            flowId = ElementId("flow_signatureDeadlineToNotSigned"),
            target = EndEventNotSigned,
          )
      }
    }

    object EventSignatureReminder : AbstractFlowNode(
      id = ElementId(EventSignatureReminder.ELEMENT_ID),
      elementType = BpmnElementType.BOUNDARY_EVENT,
      name = "7 days",
    ), HasSuccessors<EventSignatureReminder.Next>, BoundaryEvent<SubProcessConcludeContract>,
        TimerEvent {
      override val eventType: BpmnEventType = BpmnEventType.TIMER

      const val ELEMENT_ID: String = "event_signatureReminder"

      override val timer: BpmnTimer = BpmnTimer(
        type = TimerType.DURATION,
        timerValue = "P7D",
      )

      override val attachedTo: SubProcessConcludeContract
        get() = SubProcessConcludeContract

      override val isInterrupting: Boolean = false

      override val next: Next = Next

      object Next {
        val serviceTaskSendReminderMail: SequenceFlows<ServiceTaskSendReminderMail>
          get() = SequenceFlows.single(
            flowId = ElementId("flow_reminderToSendMail"),
            target = ServiceTaskSendReminderMail,
          )
      }
    }

    object EventTriggerReversal : AbstractFlowNode(
      id = ElementId(EventTriggerReversal.ELEMENT_ID),
      elementType = BpmnElementType.INTERMEDIATE_THROW_EVENT,
      name = "Trigger reversal",
    ), HasSuccessors<EventTriggerReversal.Next>, Event, CompensationThrowEvent {
      override val eventType: BpmnEventType = BpmnEventType.COMPENSATION

      const val ELEMENT_ID: String = "event_triggerReversal"

      override val next: Next = Next

      object Next {
        val serviceTaskConfirmContractCancellation:
            SequenceFlows<ServiceTaskConfirmContractCancellation>
          get() = SequenceFlows.single(
            flowId = ElementId("flow_reversalToConfirmCancellation"),
            target = ServiceTaskConfirmContractCancellation,
          )
      }
    }

    object EventWithdrawalPeriodElapsed : AbstractFlowNode(
      id = ElementId(EventWithdrawalPeriodElapsed.ELEMENT_ID),
      elementType = BpmnElementType.INTERMEDIATE_CATCH_EVENT,
      name = "Await end of withdrawal period",
    ), HasSuccessors<EventWithdrawalPeriodElapsed.Next>, Event, TimerEvent {
      override val eventType: BpmnEventType = BpmnEventType.TIMER

      const val ELEMENT_ID: String = "event_withdrawalPeriodElapsed"

      override val timer: BpmnTimer = BpmnTimer(
        type = TimerType.DURATION,
        timerValue = "P14D",
      )

      override val next: Next = Next

      object Next {
        val serviceTaskActivateLeasing: SequenceFlows<ServiceTaskActivateLeasing>
          get() = SequenceFlows.single(
            flowId = ElementId("flow_withdrawalElapsedToActive"),
            target = ServiceTaskActivateLeasing,
          )
      }
    }

    object GatewayAlternativeFound : AbstractFlowNode(
      id = ElementId(GatewayAlternativeFound.ELEMENT_ID),
      elementType = BpmnElementType.EXCLUSIVE_GATEWAY,
      name = "Alternative found?",
    ), HasSuccessors<GatewayAlternativeFound.Next> {
      const val ELEMENT_ID: String = "gateway_alternativeFound"

      override val next: Next = Next

      object Next {
        val eventTriggerReversal: SequenceFlows<EventTriggerReversal>
          get() = SequenceFlows.single(
            flowId = ElementId("flow_noAlternativeToReversal"),
            name = "No",
            conditionExpression = "=not(alternativeFound)",
            target = EventTriggerReversal,
          )

        val gatewayBikeSourceJoin: SequenceFlows<GatewayBikeSourceJoin>
          get() = SequenceFlows.single(
            flowId = ElementId("flow_alternativeFoundToBikeSource"),
            name = "Yes",
            isDefault = true,
            target = GatewayBikeSourceJoin,
          )
      }
    }

    object GatewayAwaitSignature : AbstractFlowNode(
      id = ElementId(GatewayAwaitSignature.ELEMENT_ID),
      elementType = BpmnElementType.EVENT_BASED_GATEWAY,
    ), HasSuccessors<GatewayAwaitSignature.Next> {
      const val ELEMENT_ID: String = "gateway_awaitSignature"

      override val next: Next = Next

      object Next {
        val eventContractSigned: SequenceFlows<EventContractSigned>
          get() = SequenceFlows.single(
            flowId = ElementId("flow_awaitToContractSigned"),
            target = EventContractSigned,
          )

        val eventSignatureDeadline: SequenceFlows<EventSignatureDeadline>
          get() = SequenceFlows.single(
            flowId = ElementId("flow_awaitToSignatureDeadline"),
            target = EventSignatureDeadline,
          )
      }
    }

    object GatewayBikeSourceJoin : AbstractFlowNode(
      id = ElementId(GatewayBikeSourceJoin.ELEMENT_ID),
      elementType = BpmnElementType.EXCLUSIVE_GATEWAY,
    ), HasSuccessors<GatewayBikeSourceJoin.Next> {
      const val ELEMENT_ID: String = "gateway_bikeSourceJoin"

      override val next: Next = Next

      object Next {
        val serviceTaskOrderBike: SequenceFlows<ServiceTaskOrderBike>
          get() = SequenceFlows.single(
            flowId = ElementId("flow_bikeSourceToOrder"),
            target = ServiceTaskOrderBike,
          )
      }
    }

    object GatewayFork : AbstractFlowNode(
      id = ElementId(GatewayFork.ELEMENT_ID),
      elementType = BpmnElementType.PARALLEL_GATEWAY,
    ), HasSuccessors<GatewayFork.Next> {
      const val ELEMENT_ID: String = "gateway_fork"

      override val next: Next = Next

      object Next {
        val gatewayBikeSourceJoin: SequenceFlows<GatewayBikeSourceJoin>
          get() = SequenceFlows.single(
            flowId = ElementId("flow_forkToBikeSource"),
            target = GatewayBikeSourceJoin,
          )

        val serviceTaskIssueInsurancePolicy: SequenceFlows<ServiceTaskIssueInsurancePolicy>
          get() = SequenceFlows.single(
            flowId = ElementId("flow_forkToInsurance"),
            target = ServiceTaskIssueInsurancePolicy,
          )
      }
    }

    object GatewayIsSolvent : AbstractFlowNode(
      id = ElementId(GatewayIsSolvent.ELEMENT_ID),
      elementType = BpmnElementType.EXCLUSIVE_GATEWAY,
      name = "Solvent?",
    ), HasSuccessors<GatewayIsSolvent.Next> {
      const val ELEMENT_ID: String = "gateway_isSolvent"

      override val next: Next = Next

      object Next {
        val gatewayRejectionJoin: SequenceFlows<GatewayRejectionJoin>
          get() = SequenceFlows.single(
            flowId = ElementId("flow_notSolventToRejectionJoin"),
            name = "No",
            conditionExpression = "=not(solvent)",
            target = GatewayRejectionJoin,
          )

        val subProcessConcludeContract: SequenceFlows<SubProcessConcludeContract>
          get() = SequenceFlows.single(
            flowId = ElementId("flow_solventToConcludeContract"),
            isDefault = true,
            target = SubProcessConcludeContract,
          )
      }
    }

    object GatewayJoin : AbstractFlowNode(
      id = ElementId(GatewayJoin.ELEMENT_ID),
      elementType = BpmnElementType.PARALLEL_GATEWAY,
    ), HasSuccessors<GatewayJoin.Next> {
      const val ELEMENT_ID: String = "gateway_join"

      override val next: Next = Next

      object Next {
        val eventHandoverReported: SequenceFlows<EventHandoverReported>
          get() = SequenceFlows.single(
            flowId = ElementId("flow_joinToHandover"),
            target = EventHandoverReported,
          )
      }
    }

    object GatewayRejectionJoin : AbstractFlowNode(
      id = ElementId(GatewayRejectionJoin.ELEMENT_ID),
      elementType = BpmnElementType.EXCLUSIVE_GATEWAY,
    ), HasSuccessors<GatewayRejectionJoin.Next> {
      const val ELEMENT_ID: String = "gateway_rejectionJoin"

      override val next: Next = Next

      object Next {
        val serviceTaskSendRejection: SequenceFlows<ServiceTaskSendRejection>
          get() = SequenceFlows.single(
            flowId = ElementId("flow_rejectionJoined"),
            target = ServiceTaskSendRejection,
          )
      }
    }

    object ServiceTaskActivateLeasing : AbstractFlowNode(
      id = ElementId(ServiceTaskActivateLeasing.ELEMENT_ID),
      elementType = BpmnElementType.SERVICE_TASK,
      name = "Activate leasing",
    ), HasSuccessors<ServiceTaskActivateLeasing.Next>, HasJobType {
      const val ELEMENT_ID: String = "serviceTask_activateLeasing"

      override val jobType: String = ServiceTasks.MIRAVELO_ACTIVATE_LEASING

      override val next: Next = Next

      object Next {
        val endEventLeasingActive: SequenceFlows<EndEventLeasingActive>
          get() = SequenceFlows.single(
            flowId = ElementId("flow_activateToActive"),
            target = EndEventLeasingActive,
          )
      }
    }

    object ServiceTaskCancelContract : AbstractFlowNode(
      id = ElementId(ServiceTaskCancelContract.ELEMENT_ID),
      elementType = BpmnElementType.SERVICE_TASK,
      name = "Cancel contract",
    ), HasJobType {
      const val ELEMENT_ID: String = "serviceTask_cancelContract"

      override val jobType: String = ServiceTasks.MIRAVELO_CANCEL_CONTRACT
    }

    object ServiceTaskCancelPolicy : AbstractFlowNode(
      id = ElementId(ServiceTaskCancelPolicy.ELEMENT_ID),
      elementType = BpmnElementType.SERVICE_TASK,
      name = "Cancel policy",
    ), HasJobType {
      const val ELEMENT_ID: String = "serviceTask_cancelPolicy"

      override val jobType: String = ServiceTasks.MIRAVELO_CANCEL_POLICY
    }

    object ServiceTaskConfirmContractCancellation : AbstractFlowNode(
      id = ElementId(ServiceTaskConfirmContractCancellation.ELEMENT_ID),
      elementType = BpmnElementType.SERVICE_TASK,
      name = "Send cancellation confirmation",
    ), HasSuccessors<ServiceTaskConfirmContractCancellation.Next>, HasJobType {
      const val ELEMENT_ID: String = "serviceTask_confirmContractCancellation"

      override val jobType: String = ServiceTasks.MIRAVELO_SEND_CANCELLATION_CONFIRMATION

      override val next: Next = Next

      object Next {
        val endEventContractCancelled: SequenceFlows<EndEventContractCancelled>
          get() = SequenceFlows.single(
            flowId = ElementId("flow_confirmCancellationToContractCancelled"),
            target = EndEventContractCancelled,
          )
      }
    }

    object ServiceTaskIssueInsurancePolicy : AbstractFlowNode(
      id = ElementId(ServiceTaskIssueInsurancePolicy.ELEMENT_ID),
      elementType = BpmnElementType.SERVICE_TASK,
      name = "Issue insurance policy",
    ), HasSuccessors<ServiceTaskIssueInsurancePolicy.Next>, HasJobType {
      const val ELEMENT_ID: String = "serviceTask_issueInsurancePolicy"

      override val jobType: String = ServiceTasks.MIRAVELO_ISSUE_INSURANCE_POLICY

      override val next: Next = Next

      object Next {
        val eventCompensateInsurance: AttachedBoundaryEvent<EventCompensateInsurance>
          get() = AttachedBoundaryEvent(target = EventCompensateInsurance)

        val gatewayJoin: SequenceFlows<GatewayJoin>
          get() = SequenceFlows.single(
            flowId = ElementId("flow_insuranceToJoin"),
            target = GatewayJoin,
          )
      }
    }

    object ServiceTaskOrderBike : AbstractFlowNode(
      id = ElementId(ServiceTaskOrderBike.ELEMENT_ID),
      elementType = BpmnElementType.SERVICE_TASK,
      name = "Order bike from dealer",
    ), HasSuccessors<ServiceTaskOrderBike.Next>, HasJobType, HasVariables {
      const val ELEMENT_ID: String = "serviceTask_orderBike"

      override val jobType: String = ServiceTasks.MIRAVELO_ORDER_BIKE

      override val variables: Variables = Variables

      override val next: Next = Next

      object Variables : RegisteredVariableDefinitions() {
        val ORDER_ID: VariableName.Output = output(ProcessVariables.ORDER_ID)
      }

      object Next {
        val eventBikeUnavailable: AttachedBoundaryEvent<EventBikeUnavailable>
          get() = AttachedBoundaryEvent(target = EventBikeUnavailable)

        val eventCompensateOrder: AttachedBoundaryEvent<EventCompensateOrder>
          get() = AttachedBoundaryEvent(target = EventCompensateOrder)

        val gatewayJoin: SequenceFlows<GatewayJoin>
          get() = SequenceFlows.single(
            flowId = ElementId("flow_orderToJoin"),
            target = GatewayJoin,
          )
      }
    }

    object ServiceTaskSendCancellationConfirmation : AbstractFlowNode(
      id = ElementId(ServiceTaskSendCancellationConfirmation.ELEMENT_ID),
      elementType = BpmnElementType.SERVICE_TASK,
      name = "Send cancellation confirmation",
    ), HasSuccessors<ServiceTaskSendCancellationConfirmation.Next>, HasJobType {
      const val ELEMENT_ID: String = "serviceTask_sendCancellationConfirmation"

      override val jobType: String = ServiceTasks.MIRAVELO_SEND_CANCELLATION_CONFIRMATION

      override val next: Next = Next

      object Next {
        val endEventApplicationCancelled: SequenceFlows<EndEventApplicationCancelled>
          get() = SequenceFlows.single(
            flowId = ElementId("flow_confirmationToCancelled"),
            target = EndEventApplicationCancelled,
          )
      }
    }

    object ServiceTaskSendContract : AbstractFlowNode(
      id = ElementId(ServiceTaskSendContract.ELEMENT_ID),
      elementType = BpmnElementType.SERVICE_TASK,
      name = "Send contract",
    ), HasSuccessors<ServiceTaskSendContract.Next>, HasJobType {
      const val ELEMENT_ID: String = "serviceTask_sendContract"

      override val jobType: String = ServiceTasks.MIRAVELO_SEND_CONTRACT

      override val next: Next = Next

      object Next {
        val gatewayAwaitSignature: SequenceFlows<GatewayAwaitSignature>
          get() = SequenceFlows.single(
            flowId = ElementId("flow_sendContractToAwaitSignature"),
            target = GatewayAwaitSignature,
          )
      }
    }

    object ServiceTaskSendRejection : AbstractFlowNode(
      id = ElementId(ServiceTaskSendRejection.ELEMENT_ID),
      elementType = BpmnElementType.SERVICE_TASK,
      name = "Send rejection",
    ), HasSuccessors<ServiceTaskSendRejection.Next>, HasJobType {
      const val ELEMENT_ID: String = "serviceTask_sendRejection"

      override val jobType: String = ServiceTasks.MIRAVELO_SEND_REJECTION

      override val next: Next = Next

      object Next {
        val endEventApplicationRejected: SequenceFlows<EndEventApplicationRejected>
          get() = SequenceFlows.single(
            flowId = ElementId("flow_sendRejectionToRejected"),
            target = EndEventApplicationRejected,
          )
      }
    }

    object ServiceTaskSendReminderMail : AbstractFlowNode(
      id = ElementId(ServiceTaskSendReminderMail.ELEMENT_ID),
      elementType = BpmnElementType.SERVICE_TASK,
      name = "Send reminder mail",
    ), HasSuccessors<ServiceTaskSendReminderMail.Next>, HasJobType {
      const val ELEMENT_ID: String = "serviceTask_sendReminderMail"

      override val jobType: String = ServiceTasks.MIRAVELO_SEND_REMINDER_MAIL

      override val next: Next = Next

      object Next {
        val endEventProspectReminded: SequenceFlows<EndEventProspectReminded>
          get() = SequenceFlows.single(
            flowId = ElementId("flow_sendMailToReminded"),
            target = EndEventProspectReminded,
          )
      }
    }

    object StartEventApplicationWithdrawn : AbstractFlowNode(
      id = ElementId(StartEventApplicationWithdrawn.ELEMENT_ID),
      elementType = BpmnElementType.START_EVENT,
      name = "Request withdrawn",
    ), HasSuccessors<StartEventApplicationWithdrawn.Next>, Event, HasMessage {
      override val eventType: BpmnEventType = BpmnEventType.MESSAGE

      const val ELEMENT_ID: String = "startEvent_applicationWithdrawn"

      override val message: MessageName = Messages.MIRAVELO_APPLICATION_WITHDRAWN

      val isInterrupting: Boolean = true

      override val next: Next = Next

      object Next {
        val eventReverseApplication: SequenceFlows<EventReverseApplication>
          get() = SequenceFlows.single(
            flowId = ElementId("flow_withdrawnToReverse"),
            target = EventReverseApplication,
          )
      }
    }

    object StartEventCustomerEligible : AbstractFlowNode(
      id = ElementId(StartEventCustomerEligible.ELEMENT_ID),
      elementType = BpmnElementType.START_EVENT,
      name = "Customer eligible",
    ), HasSuccessors<StartEventCustomerEligible.Next>, Event {
      override val eventType: BpmnEventType = BpmnEventType.NONE

      const val ELEMENT_ID: String = "startEvent_customerEligible"

      override val next: Next = Next

      object Next {
        val serviceTaskSendContract: SequenceFlows<ServiceTaskSendContract>
          get() = SequenceFlows.single(
            flowId = ElementId("flow_eligibleToSendContract"),
            target = ServiceTaskSendContract,
          )
      }
    }

    object StartEventLeasingRequestReceived : AbstractFlowNode(
      id = ElementId(StartEventLeasingRequestReceived.ELEMENT_ID),
      elementType = BpmnElementType.START_EVENT,
      name = "Leasing request received",
    ), HasSuccessors<StartEventLeasingRequestReceived.Next>, Event, HasMessage, HasVariables {
      override val eventType: BpmnEventType = BpmnEventType.MESSAGE

      const val ELEMENT_ID: String = "startEvent_leasingRequestReceived"

      override val message: MessageName = Messages.MIRAVELO_LEASING_REQUEST_RECEIVED

      override val variables: Variables = Variables

      override val next: Next = Next

      object Variables : RegisteredVariableDefinitions() {
        val AGE: VariableName.Output = output(ProcessVariables.AGE)

        val APPLICATION_ID: VariableName.Output = output(ProcessVariables.APPLICATION_ID)

        val BIKE_ID: VariableName.Output = output(ProcessVariables.BIKE_ID)

        val MONTHLY_NET_INCOME: VariableName.Output =
            output(ProcessVariables.MONTHLY_NET_INCOME)
      }

      object Next {
        val businessRuleTaskCheckCreditRating:
            SequenceFlows<BusinessRuleTaskCheckCreditRating>
          get() = SequenceFlows.single(
            flowId = ElementId("flow_receivedToCheckCredit"),
            target = BusinessRuleTaskCheckCreditRating,
          )
      }
    }

    object SubProcessApplicationWithdrawn : AbstractFlowNode(
      id = ElementId(SubProcessApplicationWithdrawn.ELEMENT_ID),
      elementType = BpmnElementType.EVENT_SUB_PROCESS,
      name = "Application withdrawn",
    ), FlowScope<SubProcessApplicationWithdrawn.Start> {
      const val ELEMENT_ID: String = "subProcess_applicationWithdrawn"

      override val startEvents: Start = Start

      object Start {
        val startEventApplicationWithdrawn: StartEventApplicationWithdrawn
          get() = StartEventApplicationWithdrawn
      }
    }

    object SubProcessConcludeContract : AbstractFlowNode(
      id = ElementId(SubProcessConcludeContract.ELEMENT_ID),
      elementType = BpmnElementType.SUB_PROCESS,
      name = "Conclude contract",
    ), HasSuccessors<SubProcessConcludeContract.Next>, FlowScope<SubProcessConcludeContract.Start> {
      const val ELEMENT_ID: String = "subProcess_concludeContract"

      override val next: Next = Next

      override val startEvents: Start = Start

      object Next {
        val eventCompensateContract: AttachedBoundaryEvent<EventCompensateContract>
          get() = AttachedBoundaryEvent(target = EventCompensateContract)

        val eventContractNotSigned: AttachedBoundaryEvent<EventContractNotSigned>
          get() = AttachedBoundaryEvent(target = EventContractNotSigned)

        val eventSignatureReminder: AttachedBoundaryEvent<EventSignatureReminder>
          get() = AttachedBoundaryEvent(target = EventSignatureReminder)

        val gatewayFork: SequenceFlows<GatewayFork>
          get() = SequenceFlows.single(
            flowId = ElementId("flow_concludeToFork"),
            target = GatewayFork,
          )
      }

      object Start {
        val startEventCustomerEligible: StartEventCustomerEligible
          get() = StartEventCustomerEligible
      }
    }

    object UserTaskClarifyAlternative : AbstractFlowNode(
      id = ElementId(UserTaskClarifyAlternative.ELEMENT_ID),
      elementType = BpmnElementType.USER_TASK,
      name = "Clarify alternative with customer",
    ), HasSuccessors<UserTaskClarifyAlternative.Next>, HasVariables {
      const val ELEMENT_ID: String = "userTask_clarifyAlternative"

      override val variables: Variables = Variables

      override val next: Next = Next

      object Variables : RegisteredVariableDefinitions() {
        val ALTERNATIVE_FOUND: VariableName.Output =
            output(ProcessVariables.ALTERNATIVE_FOUND)
      }

      object Next {
        val gatewayAlternativeFound: SequenceFlows<GatewayAlternativeFound>
          get() = SequenceFlows.single(
            flowId = ElementId("flow_clarifyToAlternativeFound"),
            target = GatewayAlternativeFound,
          )
      }
    }
  }
}
