// Generated by bpmn-to-code
@file:Suppress("unused")

package io.miragon.blueprint.adapter.process

import io.miragon.bpmn.runtime.BpmnErrorDefinition
import kotlin.Suppress
import kotlin.collections.List

/**
 * BPMN error definitions with name and code, as thrown and caught by the processes.
 */
object Errors {
  val BIKE_UNAVAILABLE: BpmnErrorDefinition = BpmnErrorDefinition(
    name = "Bike_Unavailable",
    code = "bikeUnavailable",
  )

  val all: List<BpmnErrorDefinition> = listOf(
    BIKE_UNAVAILABLE,
  )
}
