// Generated by bpmn-to-code
@file:Suppress("unused")

package io.miragon.blueprint.adapter.process

import io.miragon.bpmn.runtime.BpmnEscalationDefinition
import kotlin.Suppress
import kotlin.collections.List

/**
 * BPMN escalation definitions with name and code, as thrown and caught by the processes.
 */
object Escalations {
  val CONTRACT_NOT_SIGNED: BpmnEscalationDefinition = BpmnEscalationDefinition(
    name = "Contract_Not_Signed",
    code = "contractNotSigned",
  )

  val all: List<BpmnEscalationDefinition> = listOf(
    CONTRACT_NOT_SIGNED,
  )
}
