// Generated by bpmn-to-code
@file:Suppress("unused")

package io.miragon.blueprint.adapter.process

import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

/**
 * Names of the process variables used in `@Variable(name = ProcessVariables.X)` annotations.
 * Kept as `const val String` because annotation arguments must be compile-time constants.
 */
object ProcessVariables {
  const val AGE: String = "age"

  const val ALTERNATIVE_FOUND: String = "alternativeFound"

  const val APPLICATION_ID: String = "applicationId"

  const val BIKE_ID: String = "bikeId"

  const val CANCELLATION_POSSIBLE: String = "cancellationPossible"

  const val MONTHLY_NET_INCOME: String = "monthlyNetIncome"

  const val ORDER_ID: String = "orderId"

  val all: List<String> = listOf(
    AGE,
    ALTERNATIVE_FOUND,
    APPLICATION_ID,
    BIKE_ID,
    CANCELLATION_POSSIBLE,
    MONTHLY_NET_INCOME,
    ORDER_ID,
  )
}
