// Generated by bpmn-to-code
@file:Suppress("unused")

package io.miragon.blueprint.adapter.process

import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

/**
 * Job worker task types used in `@JobWorker(type = ServiceTasks.X)` annotations.
 * Kept as `const val String` because annotation arguments must be compile-time constants.
 */
object ServiceTasks {
  const val MIRAVELO_ACTIVATE_LEASING: String = "miravelo.activateLeasing"

  const val MIRAVELO_BOOK_COSTS: String = "miravelo.bookCosts"

  const val MIRAVELO_CANCEL_CONTRACT: String = "miravelo.cancelContract"

  const val MIRAVELO_CANCEL_POLICY: String = "miravelo.cancelPolicy"

  const val MIRAVELO_ISSUE_INSURANCE_POLICY: String = "miravelo.issueInsurancePolicy"

  const val MIRAVELO_ORDER_BIKE: String = "miravelo.orderBike"

  const val MIRAVELO_REQUEST_CANCELLATION: String = "miravelo.requestCancellation"

  const val MIRAVELO_SEND_CANCELLATION_CONFIRMATION: String =
      "miravelo.sendCancellationConfirmation"

  const val MIRAVELO_SEND_CONTRACT: String = "miravelo.sendContract"

  const val MIRAVELO_SEND_REJECTION: String = "miravelo.sendRejection"

  const val MIRAVELO_SEND_REMINDER_MAIL: String = "miravelo.sendReminderMail"

  val all: List<String> = listOf(
    MIRAVELO_ACTIVATE_LEASING,
    MIRAVELO_BOOK_COSTS,
    MIRAVELO_CANCEL_CONTRACT,
    MIRAVELO_CANCEL_POLICY,
    MIRAVELO_ISSUE_INSURANCE_POLICY,
    MIRAVELO_ORDER_BIKE,
    MIRAVELO_REQUEST_CANCELLATION,
    MIRAVELO_SEND_CANCELLATION_CONFIRMATION,
    MIRAVELO_SEND_CONTRACT,
    MIRAVELO_SEND_REJECTION,
    MIRAVELO_SEND_REMINDER_MAIL,
  )
}
