// Generated by bpmn-to-code
package io.miragon.blueprint.adapter.process;

import io.miragon.bpmn.runtime.AbstractFlowNode;
import io.miragon.bpmn.runtime.AssociatedCompensationHandler;
import io.miragon.bpmn.runtime.AttachedBoundaryEvent;
import io.miragon.bpmn.runtime.BoundaryEvent;
import io.miragon.bpmn.runtime.BpmnElementType;
import io.miragon.bpmn.runtime.BpmnEngine;
import io.miragon.bpmn.runtime.BpmnErrorDefinition;
import io.miragon.bpmn.runtime.BpmnEscalationDefinition;
import io.miragon.bpmn.runtime.BpmnEventType;
import io.miragon.bpmn.runtime.BpmnTimer;
import io.miragon.bpmn.runtime.CallActivity;
import io.miragon.bpmn.runtime.CompensationThrowEvent;
import io.miragon.bpmn.runtime.ElementId;
import io.miragon.bpmn.runtime.ErrorEvent;
import io.miragon.bpmn.runtime.EscalationEvent;
import io.miragon.bpmn.runtime.Event;
import io.miragon.bpmn.runtime.FlowNode;
import io.miragon.bpmn.runtime.FlowScope;
import io.miragon.bpmn.runtime.HasJobType;
import io.miragon.bpmn.runtime.HasMessage;
import io.miragon.bpmn.runtime.HasSuccessors;
import io.miragon.bpmn.runtime.HasVariables;
import io.miragon.bpmn.runtime.InputOutputMapping;
import io.miragon.bpmn.runtime.MessageName;
import io.miragon.bpmn.runtime.ProcessId;
import io.miragon.bpmn.runtime.SequenceFlows;
import io.miragon.bpmn.runtime.TimerEvent;
import io.miragon.bpmn.runtime.TimerType;
import io.miragon.bpmn.runtime.VariableDefinitions;
import io.miragon.bpmn.runtime.VariableName;
import java.util.List;

public final class BikeLeasingProcessProcessApi {
  public static final ProcessId PROCESS_ID = new ProcessId("bikeLeasingProcess");

  public static final BpmnEngine PROCESS_ENGINE = BpmnEngine.ZEEBE;

  private BikeLeasingProcessProcessApi() {
  }

  /**
   * Typed navigation over the process flow: one nested class per BPMN element.
   */
  public static final class FlowNodes {
    private FlowNodes() {
    }

    public static BusinessRuleTaskCheckCreditRating businessRuleTaskCheckCreditRating() {
      return BusinessRuleTaskCheckCreditRating.INSTANCE;
    }

    public static CallActivityCancelBikeOrder callActivityCancelBikeOrder() {
      return CallActivityCancelBikeOrder.INSTANCE;
    }

    public static EndEventApplicationCancelled endEventApplicationCancelled() {
      return EndEventApplicationCancelled.INSTANCE;
    }

    public static EndEventApplicationRejected endEventApplicationRejected() {
      return EndEventApplicationRejected.INSTANCE;
    }

    public static EndEventContractCancelled endEventContractCancelled() {
      return EndEventContractCancelled.INSTANCE;
    }

    public static EndEventContractValid endEventContractValid() {
      return EndEventContractValid.INSTANCE;
    }

    public static EndEventLeasingActive endEventLeasingActive() {
      return EndEventLeasingActive.INSTANCE;
    }

    public static EndEventNotSigned endEventNotSigned() {
      return EndEventNotSigned.INSTANCE;
    }

    public static EndEventProspectReminded endEventProspectReminded() {
      return EndEventProspectReminded.INSTANCE;
    }

    public static EventBikeUnavailable eventBikeUnavailable() {
      return EventBikeUnavailable.INSTANCE;
    }

    public static EventCompensateContract eventCompensateContract() {
      return EventCompensateContract.INSTANCE;
    }

    public static EventCompensateInsurance eventCompensateInsurance() {
      return EventCompensateInsurance.INSTANCE;
    }

    public static EventCompensateOrder eventCompensateOrder() {
      return EventCompensateOrder.INSTANCE;
    }

    public static EventContractNotSigned eventContractNotSigned() {
      return EventContractNotSigned.INSTANCE;
    }

    public static EventContractSigned eventContractSigned() {
      return EventContractSigned.INSTANCE;
    }

    public static EventHandoverReported eventHandoverReported() {
      return EventHandoverReported.INSTANCE;
    }

    public static EventReverseApplication eventReverseApplication() {
      return EventReverseApplication.INSTANCE;
    }

    public static EventSignatureDeadline eventSignatureDeadline() {
      return EventSignatureDeadline.INSTANCE;
    }

    public static EventSignatureReminder eventSignatureReminder() {
      return EventSignatureReminder.INSTANCE;
    }

    public static EventTriggerReversal eventTriggerReversal() {
      return EventTriggerReversal.INSTANCE;
    }

    public static EventWithdrawalPeriodElapsed eventWithdrawalPeriodElapsed() {
      return EventWithdrawalPeriodElapsed.INSTANCE;
    }

    public static GatewayAlternativeFound gatewayAlternativeFound() {
      return GatewayAlternativeFound.INSTANCE;
    }

    public static GatewayAwaitSignature gatewayAwaitSignature() {
      return GatewayAwaitSignature.INSTANCE;
    }

    public static GatewayBikeSourceJoin gatewayBikeSourceJoin() {
      return GatewayBikeSourceJoin.INSTANCE;
    }

    public static GatewayFork gatewayFork() {
      return GatewayFork.INSTANCE;
    }

    public static GatewayIsSolvent gatewayIsSolvent() {
      return GatewayIsSolvent.INSTANCE;
    }

    public static GatewayJoin gatewayJoin() {
      return GatewayJoin.INSTANCE;
    }

    public static GatewayRejectionJoin gatewayRejectionJoin() {
      return GatewayRejectionJoin.INSTANCE;
    }

    public static ServiceTaskActivateLeasing serviceTaskActivateLeasing() {
      return ServiceTaskActivateLeasing.INSTANCE;
    }

    public static ServiceTaskCancelContract serviceTaskCancelContract() {
      return ServiceTaskCancelContract.INSTANCE;
    }

    public static ServiceTaskCancelPolicy serviceTaskCancelPolicy() {
      return ServiceTaskCancelPolicy.INSTANCE;
    }

    public static ServiceTaskConfirmContractCancellation serviceTaskConfirmContractCancellation() {
      return ServiceTaskConfirmContractCancellation.INSTANCE;
    }

    public static ServiceTaskIssueInsurancePolicy serviceTaskIssueInsurancePolicy() {
      return ServiceTaskIssueInsurancePolicy.INSTANCE;
    }

    public static ServiceTaskOrderBike serviceTaskOrderBike() {
      return ServiceTaskOrderBike.INSTANCE;
    }

    public static ServiceTaskSendCancellationConfirmation serviceTaskSendCancellationConfirmation(
        ) {
      return ServiceTaskSendCancellationConfirmation.INSTANCE;
    }

    public static ServiceTaskSendContract serviceTaskSendContract() {
      return ServiceTaskSendContract.INSTANCE;
    }

    public static ServiceTaskSendRejection serviceTaskSendRejection() {
      return ServiceTaskSendRejection.INSTANCE;
    }

    public static ServiceTaskSendReminderMail serviceTaskSendReminderMail() {
      return ServiceTaskSendReminderMail.INSTANCE;
    }

    public static StartEventApplicationWithdrawn startEventApplicationWithdrawn() {
      return StartEventApplicationWithdrawn.INSTANCE;
    }

    public static StartEventCustomerEligible startEventCustomerEligible() {
      return StartEventCustomerEligible.INSTANCE;
    }

    public static StartEventLeasingRequestReceived startEventLeasingRequestReceived() {
      return StartEventLeasingRequestReceived.INSTANCE;
    }

    public static SubProcessApplicationWithdrawn subProcessApplicationWithdrawn() {
      return SubProcessApplicationWithdrawn.INSTANCE;
    }

    public static SubProcessConcludeContract subProcessConcludeContract() {
      return SubProcessConcludeContract.INSTANCE;
    }

    public static UserTaskClarifyAlternative userTaskClarifyAlternative() {
      return UserTaskClarifyAlternative.INSTANCE;
    }

    public static List<FlowNode> all() {
      return List.of(
          BusinessRuleTaskCheckCreditRating.INSTANCE,
          CallActivityCancelBikeOrder.INSTANCE,
          EndEventApplicationCancelled.INSTANCE,
          EndEventApplicationRejected.INSTANCE,
          EndEventContractCancelled.INSTANCE,
          EndEventContractValid.INSTANCE,
          EndEventLeasingActive.INSTANCE,
          EndEventNotSigned.INSTANCE,
          EndEventProspectReminded.INSTANCE,
          EventBikeUnavailable.INSTANCE,
          EventCompensateContract.INSTANCE,
          EventCompensateInsurance.INSTANCE,
          EventCompensateOrder.INSTANCE,
          EventContractNotSigned.INSTANCE,
          EventContractSigned.INSTANCE,
          EventHandoverReported.INSTANCE,
          EventReverseApplication.INSTANCE,
          EventSignatureDeadline.INSTANCE,
          EventSignatureReminder.INSTANCE,
          EventTriggerReversal.INSTANCE,
          EventWithdrawalPeriodElapsed.INSTANCE,
          GatewayAlternativeFound.INSTANCE,
          GatewayAwaitSignature.INSTANCE,
          GatewayBikeSourceJoin.INSTANCE,
          GatewayFork.INSTANCE,
          GatewayIsSolvent.INSTANCE,
          GatewayJoin.INSTANCE,
          GatewayRejectionJoin.INSTANCE,
          ServiceTaskActivateLeasing.INSTANCE,
          ServiceTaskCancelContract.INSTANCE,
          ServiceTaskCancelPolicy.INSTANCE,
          ServiceTaskConfirmContractCancellation.INSTANCE,
          ServiceTaskIssueInsurancePolicy.INSTANCE,
          ServiceTaskOrderBike.INSTANCE,
          ServiceTaskSendCancellationConfirmation.INSTANCE,
          ServiceTaskSendContract.INSTANCE,
          ServiceTaskSendRejection.INSTANCE,
          ServiceTaskSendReminderMail.INSTANCE,
          StartEventApplicationWithdrawn.INSTANCE,
          StartEventCustomerEligible.INSTANCE,
          StartEventLeasingRequestReceived.INSTANCE,
          SubProcessApplicationWithdrawn.INSTANCE,
          SubProcessConcludeContract.INSTANCE,
          UserTaskClarifyAlternative.INSTANCE);
    }

    public static final class BusinessRuleTaskCheckCreditRating extends AbstractFlowNode implements HasSuccessors<BusinessRuleTaskCheckCreditRating.Next> {
      public static final String ELEMENT_ID = "businessRuleTask_checkCreditRating";

      public static final BusinessRuleTaskCheckCreditRating INSTANCE = new BusinessRuleTaskCheckCreditRating();

      private BusinessRuleTaskCheckCreditRating() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.BUSINESS_RULE_TASK, "Check credit rating");
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<GatewayIsSolvent> gatewayIsSolvent() {
          return SequenceFlows.single(new ElementId("flow_checkCreditToSolvent"), GatewayIsSolvent.INSTANCE);
        }
      }
    }

    public static final class CallActivityCancelBikeOrder extends AbstractFlowNode implements CallActivity, HasVariables {
      public static final String ELEMENT_ID = "callActivity_cancelBikeOrder";

      public static final CallActivityCancelBikeOrder INSTANCE = new CallActivityCancelBikeOrder();

      private static final Variables VARIABLES = new Variables();

      private CallActivityCancelBikeOrder() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.CALL_ACTIVITY, "Cancel bike order");
      }

      @Override
      public ProcessId getCalledProcess() {
        return new ProcessId("cancelBikeOrder");
      }

      @Override
      public Variables getVariables() {
        return VARIABLES;
      }

      public static final class Variables extends VariableDefinitions {
        public static final VariableName.Input APPLICATION_ID = new VariableName.Input(ProcessVariables.APPLICATION_ID);

        public static final VariableName.Input BIKE_ID = new VariableName.Input(ProcessVariables.BIKE_ID);

        public static final VariableName.Input ORDER_ID = new VariableName.Input(ProcessVariables.ORDER_ID);

        private Variables() {
        }

        @Override
        public List<VariableName> getAll() {
          return List.of(APPLICATION_ID, BIKE_ID, ORDER_ID);
        }
      }

      public static final class Inputs {
        public static final InputOutputMapping APPLICATION_ID = new InputOutputMapping("applicationId", "=applicationId", null);

        public static final InputOutputMapping BIKE_ID = new InputOutputMapping("bikeId", "=bikeId", null);

        public static final InputOutputMapping ORDER_ID = new InputOutputMapping("orderId", "=orderId", null);

        private Inputs() {
        }
      }
    }

    public static final class EndEventApplicationCancelled extends AbstractFlowNode implements Event {
      public static final String ELEMENT_ID = "endEvent_applicationCancelled";

      public static final EndEventApplicationCancelled INSTANCE = new EndEventApplicationCancelled();

      private EndEventApplicationCancelled() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.END_EVENT, "Leasing cancelled");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.NONE;
      }
    }

    public static final class EndEventApplicationRejected extends AbstractFlowNode implements Event {
      public static final String ELEMENT_ID = "endEvent_applicationRejected";

      public static final EndEventApplicationRejected INSTANCE = new EndEventApplicationRejected();

      private EndEventApplicationRejected() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.END_EVENT, "Application rejected");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.NONE;
      }
    }

    public static final class EndEventContractCancelled extends AbstractFlowNode implements Event {
      public static final String ELEMENT_ID = "endEvent_contractCancelled";

      public static final EndEventContractCancelled INSTANCE = new EndEventContractCancelled();

      private EndEventContractCancelled() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.END_EVENT, "Contract cancelled");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.TERMINATE;
      }
    }

    public static final class EndEventContractValid extends AbstractFlowNode implements Event {
      public static final String ELEMENT_ID = "endEvent_contractValid";

      public static final EndEventContractValid INSTANCE = new EndEventContractValid();

      private EndEventContractValid() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.END_EVENT, "Contract valid");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.NONE;
      }
    }

    public static final class EndEventLeasingActive extends AbstractFlowNode implements Event {
      public static final String ELEMENT_ID = "endEvent_leasingActive";

      public static final EndEventLeasingActive INSTANCE = new EndEventLeasingActive();

      private EndEventLeasingActive() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.END_EVENT, "Leasing active");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.NONE;
      }
    }

    public static final class EndEventNotSigned extends AbstractFlowNode implements Event, EscalationEvent {
      public static final String ELEMENT_ID = "endEvent_notSigned";

      public static final EndEventNotSigned INSTANCE = new EndEventNotSigned();

      private EndEventNotSigned() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.END_EVENT, "Not signed");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.ESCALATION;
      }

      @Override
      public BpmnEscalationDefinition getEscalation() {
        return Escalations.CONTRACT_NOT_SIGNED;
      }
    }

    public static final class EndEventProspectReminded extends AbstractFlowNode implements Event {
      public static final String ELEMENT_ID = "endEvent_prospectReminded";

      public static final EndEventProspectReminded INSTANCE = new EndEventProspectReminded();

      private EndEventProspectReminded() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.END_EVENT, "Prospect reminded");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.NONE;
      }
    }

    public static final class EventBikeUnavailable extends AbstractFlowNode implements HasSuccessors<EventBikeUnavailable.Next>, BoundaryEvent<ServiceTaskOrderBike>, ErrorEvent {
      public static final String ELEMENT_ID = "event_bikeUnavailable";

      public static final EventBikeUnavailable INSTANCE = new EventBikeUnavailable();

      private EventBikeUnavailable() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.BOUNDARY_EVENT, "Bike unavailable");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.ERROR;
      }

      @Override
      public BpmnErrorDefinition getError() {
        return Errors.BIKE_UNAVAILABLE;
      }

      @Override
      public ServiceTaskOrderBike getAttachedTo() {
        return ServiceTaskOrderBike.INSTANCE;
      }

      @Override
      public boolean isInterrupting() {
        return true;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<UserTaskClarifyAlternative> userTaskClarifyAlternative() {
          return SequenceFlows.single(new ElementId("flow_bikeUnavailableToClarify"), UserTaskClarifyAlternative.INSTANCE);
        }
      }
    }

    public static final class EventCompensateContract extends AbstractFlowNode implements HasSuccessors<EventCompensateContract.Next>, BoundaryEvent<SubProcessConcludeContract> {
      public static final String ELEMENT_ID = "event_compensateContract";

      public static final EventCompensateContract INSTANCE = new EventCompensateContract();

      private EventCompensateContract() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.BOUNDARY_EVENT, "Compensate contract");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.COMPENSATION;
      }

      @Override
      public SubProcessConcludeContract getAttachedTo() {
        return SubProcessConcludeContract.INSTANCE;
      }

      @Override
      public boolean isInterrupting() {
        return true;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public AssociatedCompensationHandler<ServiceTaskCancelContract> serviceTaskCancelContract(
            ) {
          return new AssociatedCompensationHandler<>(ServiceTaskCancelContract.INSTANCE);
        }
      }
    }

    public static final class EventCompensateInsurance extends AbstractFlowNode implements HasSuccessors<EventCompensateInsurance.Next>, BoundaryEvent<ServiceTaskIssueInsurancePolicy> {
      public static final String ELEMENT_ID = "event_compensateInsurance";

      public static final EventCompensateInsurance INSTANCE = new EventCompensateInsurance();

      private EventCompensateInsurance() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.BOUNDARY_EVENT, "Compensate policy");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.COMPENSATION;
      }

      @Override
      public ServiceTaskIssueInsurancePolicy getAttachedTo() {
        return ServiceTaskIssueInsurancePolicy.INSTANCE;
      }

      @Override
      public boolean isInterrupting() {
        return true;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public AssociatedCompensationHandler<ServiceTaskCancelPolicy> serviceTaskCancelPolicy() {
          return new AssociatedCompensationHandler<>(ServiceTaskCancelPolicy.INSTANCE);
        }
      }
    }

    public static final class EventCompensateOrder extends AbstractFlowNode implements HasSuccessors<EventCompensateOrder.Next>, BoundaryEvent<ServiceTaskOrderBike> {
      public static final String ELEMENT_ID = "event_compensateOrder";

      public static final EventCompensateOrder INSTANCE = new EventCompensateOrder();

      private EventCompensateOrder() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.BOUNDARY_EVENT, "Compensate order");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.COMPENSATION;
      }

      @Override
      public ServiceTaskOrderBike getAttachedTo() {
        return ServiceTaskOrderBike.INSTANCE;
      }

      @Override
      public boolean isInterrupting() {
        return true;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public AssociatedCompensationHandler<CallActivityCancelBikeOrder> callActivityCancelBikeOrder(
            ) {
          return new AssociatedCompensationHandler<>(CallActivityCancelBikeOrder.INSTANCE);
        }
      }
    }

    public static final class EventContractNotSigned extends AbstractFlowNode implements HasSuccessors<EventContractNotSigned.Next>, BoundaryEvent<SubProcessConcludeContract>, EscalationEvent {
      public static final String ELEMENT_ID = "event_contractNotSigned";

      public static final EventContractNotSigned INSTANCE = new EventContractNotSigned();

      private EventContractNotSigned() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.BOUNDARY_EVENT, "Contract not signed");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.ESCALATION;
      }

      @Override
      public BpmnEscalationDefinition getEscalation() {
        return Escalations.CONTRACT_NOT_SIGNED;
      }

      @Override
      public SubProcessConcludeContract getAttachedTo() {
        return SubProcessConcludeContract.INSTANCE;
      }

      @Override
      public boolean isInterrupting() {
        return true;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<GatewayRejectionJoin> gatewayRejectionJoin() {
          return SequenceFlows.single(new ElementId("flow_notSignedToRejectionJoin"), GatewayRejectionJoin.INSTANCE);
        }
      }
    }

    public static final class EventContractSigned extends AbstractFlowNode implements HasSuccessors<EventContractSigned.Next>, Event, HasMessage {
      public static final String ELEMENT_ID = "event_contractSigned";

      public static final EventContractSigned INSTANCE = new EventContractSigned();

      private EventContractSigned() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.INTERMEDIATE_CATCH_EVENT, "Contract signed");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.MESSAGE;
      }

      @Override
      public MessageName getMessage() {
        return Messages.MIRAVELO_CONTRACT_SIGNED;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<EndEventContractValid> endEventContractValid() {
          return SequenceFlows.single(new ElementId("flow_contractSignedToValid"), EndEventContractValid.INSTANCE);
        }
      }
    }

    public static final class EventHandoverReported extends AbstractFlowNode implements HasSuccessors<EventHandoverReported.Next>, Event, HasMessage {
      public static final String ELEMENT_ID = "event_handoverReported";

      public static final EventHandoverReported INSTANCE = new EventHandoverReported();

      private EventHandoverReported() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.INTERMEDIATE_CATCH_EVENT, "Handover reported");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.MESSAGE;
      }

      @Override
      public MessageName getMessage() {
        return Messages.MIRAVELO_HANDOVER_REPORTED;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<EventWithdrawalPeriodElapsed> eventWithdrawalPeriodElapsed() {
          return SequenceFlows.single(new ElementId("flow_handoverToWithdrawalPeriod"), EventWithdrawalPeriodElapsed.INSTANCE);
        }
      }
    }

    public static final class EventReverseApplication extends AbstractFlowNode implements HasSuccessors<EventReverseApplication.Next>, Event, CompensationThrowEvent {
      public static final String ELEMENT_ID = "event_reverseApplication";

      public static final EventReverseApplication INSTANCE = new EventReverseApplication();

      private EventReverseApplication() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.INTERMEDIATE_THROW_EVENT, "Reverse application");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.COMPENSATION;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<ServiceTaskSendCancellationConfirmation> serviceTaskSendCancellationConfirmation(
            ) {
          return SequenceFlows.single(new ElementId("flow_reverseToSendConfirmation"), ServiceTaskSendCancellationConfirmation.INSTANCE);
        }
      }
    }

    public static final class EventSignatureDeadline extends AbstractFlowNode implements HasSuccessors<EventSignatureDeadline.Next>, Event, TimerEvent {
      public static final String ELEMENT_ID = "event_signatureDeadline";

      public static final EventSignatureDeadline INSTANCE = new EventSignatureDeadline();

      private EventSignatureDeadline() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.INTERMEDIATE_CATCH_EVENT, "14 days");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.TIMER;
      }

      @Override
      public BpmnTimer getTimer() {
        return new BpmnTimer(TimerType.DURATION, "P14D");
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<EndEventNotSigned> endEventNotSigned() {
          return SequenceFlows.single(new ElementId("flow_signatureDeadlineToNotSigned"), EndEventNotSigned.INSTANCE);
        }
      }
    }

    public static final class EventSignatureReminder extends AbstractFlowNode implements HasSuccessors<EventSignatureReminder.Next>, BoundaryEvent<SubProcessConcludeContract>, TimerEvent {
      public static final String ELEMENT_ID = "event_signatureReminder";

      public static final EventSignatureReminder INSTANCE = new EventSignatureReminder();

      private EventSignatureReminder() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.BOUNDARY_EVENT, "7 days");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.TIMER;
      }

      @Override
      public BpmnTimer getTimer() {
        return new BpmnTimer(TimerType.DURATION, "P7D");
      }

      @Override
      public SubProcessConcludeContract getAttachedTo() {
        return SubProcessConcludeContract.INSTANCE;
      }

      @Override
      public boolean isInterrupting() {
        return false;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<ServiceTaskSendReminderMail> serviceTaskSendReminderMail() {
          return SequenceFlows.single(new ElementId("flow_reminderToSendMail"), ServiceTaskSendReminderMail.INSTANCE);
        }
      }
    }

    public static final class EventTriggerReversal extends AbstractFlowNode implements HasSuccessors<EventTriggerReversal.Next>, Event, CompensationThrowEvent {
      public static final String ELEMENT_ID = "event_triggerReversal";

      public static final EventTriggerReversal INSTANCE = new EventTriggerReversal();

      private EventTriggerReversal() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.INTERMEDIATE_THROW_EVENT, "Trigger reversal");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.COMPENSATION;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<ServiceTaskConfirmContractCancellation> serviceTaskConfirmContractCancellation(
            ) {
          return SequenceFlows.single(new ElementId("flow_reversalToConfirmCancellation"), ServiceTaskConfirmContractCancellation.INSTANCE);
        }
      }
    }

    public static final class EventWithdrawalPeriodElapsed extends AbstractFlowNode implements HasSuccessors<EventWithdrawalPeriodElapsed.Next>, Event, TimerEvent {
      public static final String ELEMENT_ID = "event_withdrawalPeriodElapsed";

      public static final EventWithdrawalPeriodElapsed INSTANCE = new EventWithdrawalPeriodElapsed();

      private EventWithdrawalPeriodElapsed() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.INTERMEDIATE_CATCH_EVENT, "Await end of withdrawal period");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.TIMER;
      }

      @Override
      public BpmnTimer getTimer() {
        return new BpmnTimer(TimerType.DURATION, "P14D");
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<ServiceTaskActivateLeasing> serviceTaskActivateLeasing() {
          return SequenceFlows.single(new ElementId("flow_withdrawalElapsedToActive"), ServiceTaskActivateLeasing.INSTANCE);
        }
      }
    }

    public static final class GatewayAlternativeFound extends AbstractFlowNode implements HasSuccessors<GatewayAlternativeFound.Next> {
      public static final String ELEMENT_ID = "gateway_alternativeFound";

      public static final GatewayAlternativeFound INSTANCE = new GatewayAlternativeFound();

      private GatewayAlternativeFound() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.EXCLUSIVE_GATEWAY, "Alternative found?");
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<EventTriggerReversal> eventTriggerReversal() {
          return SequenceFlows.single(new ElementId("flow_noAlternativeToReversal"), "No", "=not(alternativeFound)", false, EventTriggerReversal.INSTANCE);
        }

        public SequenceFlows<GatewayBikeSourceJoin> gatewayBikeSourceJoin() {
          return SequenceFlows.single(new ElementId("flow_alternativeFoundToBikeSource"), "Yes", null, true, GatewayBikeSourceJoin.INSTANCE);
        }
      }
    }

    public static final class GatewayAwaitSignature extends AbstractFlowNode implements HasSuccessors<GatewayAwaitSignature.Next> {
      public static final String ELEMENT_ID = "gateway_awaitSignature";

      public static final GatewayAwaitSignature INSTANCE = new GatewayAwaitSignature();

      private GatewayAwaitSignature() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.EVENT_BASED_GATEWAY);
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<EventContractSigned> eventContractSigned() {
          return SequenceFlows.single(new ElementId("flow_awaitToContractSigned"), EventContractSigned.INSTANCE);
        }

        public SequenceFlows<EventSignatureDeadline> eventSignatureDeadline() {
          return SequenceFlows.single(new ElementId("flow_awaitToSignatureDeadline"), EventSignatureDeadline.INSTANCE);
        }
      }
    }

    public static final class GatewayBikeSourceJoin extends AbstractFlowNode implements HasSuccessors<GatewayBikeSourceJoin.Next> {
      public static final String ELEMENT_ID = "gateway_bikeSourceJoin";

      public static final GatewayBikeSourceJoin INSTANCE = new GatewayBikeSourceJoin();

      private GatewayBikeSourceJoin() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.EXCLUSIVE_GATEWAY);
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<ServiceTaskOrderBike> serviceTaskOrderBike() {
          return SequenceFlows.single(new ElementId("flow_bikeSourceToOrder"), ServiceTaskOrderBike.INSTANCE);
        }
      }
    }

    public static final class GatewayFork extends AbstractFlowNode implements HasSuccessors<GatewayFork.Next> {
      public static final String ELEMENT_ID = "gateway_fork";

      public static final GatewayFork INSTANCE = new GatewayFork();

      private GatewayFork() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.PARALLEL_GATEWAY);
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<GatewayBikeSourceJoin> gatewayBikeSourceJoin() {
          return SequenceFlows.single(new ElementId("flow_forkToBikeSource"), GatewayBikeSourceJoin.INSTANCE);
        }

        public SequenceFlows<ServiceTaskIssueInsurancePolicy> serviceTaskIssueInsurancePolicy() {
          return SequenceFlows.single(new ElementId("flow_forkToInsurance"), ServiceTaskIssueInsurancePolicy.INSTANCE);
        }
      }
    }

    public static final class GatewayIsSolvent extends AbstractFlowNode implements HasSuccessors<GatewayIsSolvent.Next> {
      public static final String ELEMENT_ID = "gateway_isSolvent";

      public static final GatewayIsSolvent INSTANCE = new GatewayIsSolvent();

      private GatewayIsSolvent() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.EXCLUSIVE_GATEWAY, "Solvent?");
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<GatewayRejectionJoin> gatewayRejectionJoin() {
          return SequenceFlows.single(new ElementId("flow_notSolventToRejectionJoin"), "No", "=not(solvent)", false, GatewayRejectionJoin.INSTANCE);
        }

        public SequenceFlows<SubProcessConcludeContract> subProcessConcludeContract() {
          return SequenceFlows.single(new ElementId("flow_solventToConcludeContract"), null, null, true, SubProcessConcludeContract.INSTANCE);
        }
      }
    }

    public static final class GatewayJoin extends AbstractFlowNode implements HasSuccessors<GatewayJoin.Next> {
      public static final String ELEMENT_ID = "gateway_join";

      public static final GatewayJoin INSTANCE = new GatewayJoin();

      private GatewayJoin() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.PARALLEL_GATEWAY);
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<EventHandoverReported> eventHandoverReported() {
          return SequenceFlows.single(new ElementId("flow_joinToHandover"), EventHandoverReported.INSTANCE);
        }
      }
    }

    public static final class GatewayRejectionJoin extends AbstractFlowNode implements HasSuccessors<GatewayRejectionJoin.Next> {
      public static final String ELEMENT_ID = "gateway_rejectionJoin";

      public static final GatewayRejectionJoin INSTANCE = new GatewayRejectionJoin();

      private GatewayRejectionJoin() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.EXCLUSIVE_GATEWAY);
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<ServiceTaskSendRejection> serviceTaskSendRejection() {
          return SequenceFlows.single(new ElementId("flow_rejectionJoined"), ServiceTaskSendRejection.INSTANCE);
        }
      }
    }

    public static final class ServiceTaskActivateLeasing extends AbstractFlowNode implements HasSuccessors<ServiceTaskActivateLeasing.Next>, HasJobType {
      public static final String ELEMENT_ID = "serviceTask_activateLeasing";

      public static final ServiceTaskActivateLeasing INSTANCE = new ServiceTaskActivateLeasing();

      private ServiceTaskActivateLeasing() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.SERVICE_TASK, "Activate leasing");
      }

      @Override
      public String getJobType() {
        return ServiceTasks.MIRAVELO_ACTIVATE_LEASING;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<EndEventLeasingActive> endEventLeasingActive() {
          return SequenceFlows.single(new ElementId("flow_activateToActive"), EndEventLeasingActive.INSTANCE);
        }
      }
    }

    public static final class ServiceTaskCancelContract extends AbstractFlowNode implements HasJobType {
      public static final String ELEMENT_ID = "serviceTask_cancelContract";

      public static final ServiceTaskCancelContract INSTANCE = new ServiceTaskCancelContract();

      private ServiceTaskCancelContract() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.SERVICE_TASK, "Cancel contract");
      }

      @Override
      public String getJobType() {
        return ServiceTasks.MIRAVELO_CANCEL_CONTRACT;
      }
    }

    public static final class ServiceTaskCancelPolicy extends AbstractFlowNode implements HasJobType {
      public static final String ELEMENT_ID = "serviceTask_cancelPolicy";

      public static final ServiceTaskCancelPolicy INSTANCE = new ServiceTaskCancelPolicy();

      private ServiceTaskCancelPolicy() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.SERVICE_TASK, "Cancel policy");
      }

      @Override
      public String getJobType() {
        return ServiceTasks.MIRAVELO_CANCEL_POLICY;
      }
    }

    public static final class ServiceTaskConfirmContractCancellation extends AbstractFlowNode implements HasSuccessors<ServiceTaskConfirmContractCancellation.Next>, HasJobType {
      public static final String ELEMENT_ID = "serviceTask_confirmContractCancellation";

      public static final ServiceTaskConfirmContractCancellation INSTANCE = new ServiceTaskConfirmContractCancellation();

      private ServiceTaskConfirmContractCancellation() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.SERVICE_TASK, "Send cancellation confirmation");
      }

      @Override
      public String getJobType() {
        return ServiceTasks.MIRAVELO_SEND_CANCELLATION_CONFIRMATION;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<EndEventContractCancelled> endEventContractCancelled() {
          return SequenceFlows.single(new ElementId("flow_confirmCancellationToContractCancelled"), EndEventContractCancelled.INSTANCE);
        }
      }
    }

    public static final class ServiceTaskIssueInsurancePolicy extends AbstractFlowNode implements HasSuccessors<ServiceTaskIssueInsurancePolicy.Next>, HasJobType {
      public static final String ELEMENT_ID = "serviceTask_issueInsurancePolicy";

      public static final ServiceTaskIssueInsurancePolicy INSTANCE = new ServiceTaskIssueInsurancePolicy();

      private ServiceTaskIssueInsurancePolicy() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.SERVICE_TASK, "Issue insurance policy");
      }

      @Override
      public String getJobType() {
        return ServiceTasks.MIRAVELO_ISSUE_INSURANCE_POLICY;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public AttachedBoundaryEvent<EventCompensateInsurance> eventCompensateInsurance() {
          return new AttachedBoundaryEvent<>(EventCompensateInsurance.INSTANCE);
        }

        public SequenceFlows<GatewayJoin> gatewayJoin() {
          return SequenceFlows.single(new ElementId("flow_insuranceToJoin"), GatewayJoin.INSTANCE);
        }
      }
    }

    public static final class ServiceTaskOrderBike extends AbstractFlowNode implements HasSuccessors<ServiceTaskOrderBike.Next>, HasJobType, HasVariables {
      public static final String ELEMENT_ID = "serviceTask_orderBike";

      public static final ServiceTaskOrderBike INSTANCE = new ServiceTaskOrderBike();

      private static final Variables VARIABLES = new Variables();

      private ServiceTaskOrderBike() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.SERVICE_TASK, "Order bike from dealer");
      }

      @Override
      public String getJobType() {
        return ServiceTasks.MIRAVELO_ORDER_BIKE;
      }

      @Override
      public Variables getVariables() {
        return VARIABLES;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Variables extends VariableDefinitions {
        public static final VariableName.Input BIKE_ID = new VariableName.Input(ProcessVariables.BIKE_ID);

        public static final VariableName.Output ORDER_ID = new VariableName.Output(ProcessVariables.ORDER_ID);

        private Variables() {
        }

        @Override
        public List<VariableName> getAll() {
          return List.of(BIKE_ID, ORDER_ID);
        }
      }

      public static final class Next {
        public AttachedBoundaryEvent<EventBikeUnavailable> eventBikeUnavailable() {
          return new AttachedBoundaryEvent<>(EventBikeUnavailable.INSTANCE);
        }

        public AttachedBoundaryEvent<EventCompensateOrder> eventCompensateOrder() {
          return new AttachedBoundaryEvent<>(EventCompensateOrder.INSTANCE);
        }

        public SequenceFlows<GatewayJoin> gatewayJoin() {
          return SequenceFlows.single(new ElementId("flow_orderToJoin"), GatewayJoin.INSTANCE);
        }
      }
    }

    public static final class ServiceTaskSendCancellationConfirmation extends AbstractFlowNode implements HasSuccessors<ServiceTaskSendCancellationConfirmation.Next>, HasJobType {
      public static final String ELEMENT_ID = "serviceTask_sendCancellationConfirmation";

      public static final ServiceTaskSendCancellationConfirmation INSTANCE = new ServiceTaskSendCancellationConfirmation();

      private ServiceTaskSendCancellationConfirmation() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.SERVICE_TASK, "Send cancellation confirmation");
      }

      @Override
      public String getJobType() {
        return ServiceTasks.MIRAVELO_SEND_CANCELLATION_CONFIRMATION;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<EndEventApplicationCancelled> endEventApplicationCancelled() {
          return SequenceFlows.single(new ElementId("flow_confirmationToCancelled"), EndEventApplicationCancelled.INSTANCE);
        }
      }
    }

    public static final class ServiceTaskSendContract extends AbstractFlowNode implements HasSuccessors<ServiceTaskSendContract.Next>, HasJobType {
      public static final String ELEMENT_ID = "serviceTask_sendContract";

      public static final ServiceTaskSendContract INSTANCE = new ServiceTaskSendContract();

      private ServiceTaskSendContract() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.SERVICE_TASK, "Send contract");
      }

      @Override
      public String getJobType() {
        return ServiceTasks.MIRAVELO_SEND_CONTRACT;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<GatewayAwaitSignature> gatewayAwaitSignature() {
          return SequenceFlows.single(new ElementId("flow_sendContractToAwaitSignature"), GatewayAwaitSignature.INSTANCE);
        }
      }
    }

    public static final class ServiceTaskSendRejection extends AbstractFlowNode implements HasSuccessors<ServiceTaskSendRejection.Next>, HasJobType {
      public static final String ELEMENT_ID = "serviceTask_sendRejection";

      public static final ServiceTaskSendRejection INSTANCE = new ServiceTaskSendRejection();

      private ServiceTaskSendRejection() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.SERVICE_TASK, "Send rejection");
      }

      @Override
      public String getJobType() {
        return ServiceTasks.MIRAVELO_SEND_REJECTION;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<EndEventApplicationRejected> endEventApplicationRejected() {
          return SequenceFlows.single(new ElementId("flow_sendRejectionToRejected"), EndEventApplicationRejected.INSTANCE);
        }
      }
    }

    public static final class ServiceTaskSendReminderMail extends AbstractFlowNode implements HasSuccessors<ServiceTaskSendReminderMail.Next>, HasJobType {
      public static final String ELEMENT_ID = "serviceTask_sendReminderMail";

      public static final ServiceTaskSendReminderMail INSTANCE = new ServiceTaskSendReminderMail();

      private ServiceTaskSendReminderMail() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.SERVICE_TASK, "Send reminder mail");
      }

      @Override
      public String getJobType() {
        return ServiceTasks.MIRAVELO_SEND_REMINDER_MAIL;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<EndEventProspectReminded> endEventProspectReminded() {
          return SequenceFlows.single(new ElementId("flow_sendMailToReminded"), EndEventProspectReminded.INSTANCE);
        }
      }
    }

    public static final class StartEventApplicationWithdrawn extends AbstractFlowNode implements HasSuccessors<StartEventApplicationWithdrawn.Next>, Event, HasMessage {
      public static final String ELEMENT_ID = "startEvent_applicationWithdrawn";

      public static final StartEventApplicationWithdrawn INSTANCE = new StartEventApplicationWithdrawn();

      private StartEventApplicationWithdrawn() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.START_EVENT, "Request withdrawn");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.MESSAGE;
      }

      @Override
      public MessageName getMessage() {
        return Messages.MIRAVELO_APPLICATION_WITHDRAWN;
      }

      public boolean isInterrupting() {
        return true;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<EventReverseApplication> eventReverseApplication() {
          return SequenceFlows.single(new ElementId("flow_withdrawnToReverse"), EventReverseApplication.INSTANCE);
        }
      }
    }

    public static final class StartEventCustomerEligible extends AbstractFlowNode implements HasSuccessors<StartEventCustomerEligible.Next>, Event {
      public static final String ELEMENT_ID = "startEvent_customerEligible";

      public static final StartEventCustomerEligible INSTANCE = new StartEventCustomerEligible();

      private StartEventCustomerEligible() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.START_EVENT, "Customer eligible");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.NONE;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<ServiceTaskSendContract> serviceTaskSendContract() {
          return SequenceFlows.single(new ElementId("flow_eligibleToSendContract"), ServiceTaskSendContract.INSTANCE);
        }
      }
    }

    public static final class StartEventLeasingRequestReceived extends AbstractFlowNode implements HasSuccessors<StartEventLeasingRequestReceived.Next>,
        Event,
        HasMessage,
        HasVariables {
      public static final String ELEMENT_ID = "startEvent_leasingRequestReceived";

      public static final StartEventLeasingRequestReceived INSTANCE = new StartEventLeasingRequestReceived();

      private static final Variables VARIABLES = new Variables();

      private StartEventLeasingRequestReceived() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.START_EVENT, "Leasing request received");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.MESSAGE;
      }

      @Override
      public MessageName getMessage() {
        return Messages.MIRAVELO_LEASING_REQUEST_RECEIVED;
      }

      @Override
      public Variables getVariables() {
        return VARIABLES;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Variables extends VariableDefinitions {
        public static final VariableName.Output AGE = new VariableName.Output(ProcessVariables.AGE);

        public static final VariableName.Output APPLICATION_ID = new VariableName.Output(ProcessVariables.APPLICATION_ID);

        public static final VariableName.Output BIKE_ID = new VariableName.Output(ProcessVariables.BIKE_ID);

        public static final VariableName.Output MONTHLY_NET_INCOME = new VariableName.Output(ProcessVariables.MONTHLY_NET_INCOME);

        private Variables() {
        }

        @Override
        public List<VariableName> getAll() {
          return List.of(AGE, APPLICATION_ID, BIKE_ID, MONTHLY_NET_INCOME);
        }
      }

      public static final class Next {
        public SequenceFlows<BusinessRuleTaskCheckCreditRating> businessRuleTaskCheckCreditRating(
            ) {
          return SequenceFlows.single(new ElementId("flow_receivedToCheckCredit"), BusinessRuleTaskCheckCreditRating.INSTANCE);
        }
      }
    }

    public static final class SubProcessApplicationWithdrawn extends AbstractFlowNode implements FlowScope<SubProcessApplicationWithdrawn.Start> {
      public static final String ELEMENT_ID = "subProcess_applicationWithdrawn";

      public static final SubProcessApplicationWithdrawn INSTANCE = new SubProcessApplicationWithdrawn();

      private SubProcessApplicationWithdrawn() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.EVENT_SUB_PROCESS, "Application withdrawn");
      }

      @Override
      public Start getStartEvents() {
        return new Start();
      }

      public static final class Start {
        public StartEventApplicationWithdrawn startEventApplicationWithdrawn() {
          return StartEventApplicationWithdrawn.INSTANCE;
        }
      }
    }

    public static final class SubProcessConcludeContract extends AbstractFlowNode implements HasSuccessors<SubProcessConcludeContract.Next>, FlowScope<SubProcessConcludeContract.Start> {
      public static final String ELEMENT_ID = "subProcess_concludeContract";

      public static final SubProcessConcludeContract INSTANCE = new SubProcessConcludeContract();

      private SubProcessConcludeContract() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.SUB_PROCESS, "Conclude contract");
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      @Override
      public Start getStartEvents() {
        return new Start();
      }

      public static final class Next {
        public AttachedBoundaryEvent<EventCompensateContract> eventCompensateContract() {
          return new AttachedBoundaryEvent<>(EventCompensateContract.INSTANCE);
        }

        public AttachedBoundaryEvent<EventContractNotSigned> eventContractNotSigned() {
          return new AttachedBoundaryEvent<>(EventContractNotSigned.INSTANCE);
        }

        public AttachedBoundaryEvent<EventSignatureReminder> eventSignatureReminder() {
          return new AttachedBoundaryEvent<>(EventSignatureReminder.INSTANCE);
        }

        public SequenceFlows<GatewayFork> gatewayFork() {
          return SequenceFlows.single(new ElementId("flow_concludeToFork"), GatewayFork.INSTANCE);
        }
      }

      public static final class Start {
        public StartEventCustomerEligible startEventCustomerEligible() {
          return StartEventCustomerEligible.INSTANCE;
        }
      }
    }

    public static final class UserTaskClarifyAlternative extends AbstractFlowNode implements HasSuccessors<UserTaskClarifyAlternative.Next>, HasVariables {
      public static final String ELEMENT_ID = "userTask_clarifyAlternative";

      public static final UserTaskClarifyAlternative INSTANCE = new UserTaskClarifyAlternative();

      private static final Variables VARIABLES = new Variables();

      private UserTaskClarifyAlternative() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.USER_TASK, "Clarify alternative with customer");
      }

      @Override
      public Variables getVariables() {
        return VARIABLES;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Variables extends VariableDefinitions {
        public static final VariableName.Output ALTERNATIVE_FOUND = new VariableName.Output(ProcessVariables.ALTERNATIVE_FOUND);

        public static final VariableName.Output BIKE_ID = new VariableName.Output(ProcessVariables.BIKE_ID);

        private Variables() {
        }

        @Override
        public List<VariableName> getAll() {
          return List.of(ALTERNATIVE_FOUND, BIKE_ID);
        }
      }

      public static final class Next {
        public SequenceFlows<GatewayAlternativeFound> gatewayAlternativeFound() {
          return SequenceFlows.single(new ElementId("flow_clarifyToAlternativeFound"), GatewayAlternativeFound.INSTANCE);
        }
      }
    }
  }
}
