// Generated by bpmn-to-code
package io.miragon.blueprint.adapter.process;

import io.miragon.bpmn.runtime.BpmnErrorDefinition;
import java.util.List;

/**
 * BPMN error definitions with name and code, as thrown and caught by the processes.
 */
public final class Errors {
  public static final BpmnErrorDefinition BIKE_UNAVAILABLE = new BpmnErrorDefinition("Bike_Unavailable", "bikeUnavailable");

  private Errors() {
  }

  public static List<BpmnErrorDefinition> all() {
    return List.of(
        BIKE_UNAVAILABLE);
  }
}
