// Generated by bpmn-to-code
package io.miragon.blueprint.adapter.process;

import io.miragon.bpmn.runtime.MessageName;
import java.util.List;

/**
 * BPMN message names used to correlate messages to running process instances.
 */
public final class Messages {
  public static final MessageName MIRAVELO_APPLICATION_WITHDRAWN = new MessageName("miravelo.applicationWithdrawn");

  public static final MessageName MIRAVELO_CONTRACT_SIGNED = new MessageName("miravelo.contractSigned");

  public static final MessageName MIRAVELO_HANDOVER_REPORTED = new MessageName("miravelo.handoverReported");

  public static final MessageName MIRAVELO_LEASING_REQUEST_RECEIVED = new MessageName("miravelo.leasingRequestReceived");

  private Messages() {
  }

  public static List<MessageName> all() {
    return List.of(
        MIRAVELO_APPLICATION_WITHDRAWN,
        MIRAVELO_CONTRACT_SIGNED,
        MIRAVELO_HANDOVER_REPORTED,
        MIRAVELO_LEASING_REQUEST_RECEIVED);
  }
}
