// Generated by bpmn-to-code
package io.miragon.blueprint.adapter.process;

import java.util.List;

/**
 * Names of the process variables used in {@code @Variable(name = ProcessVariables.X)} annotations.
 * Kept as {@code public static final String} because annotation arguments must be compile-time constants.
 */
public final class ProcessVariables {
  public static final String AGE = "age";

  public static final String ALTERNATIVE_FOUND = "alternativeFound";

  public static final String APPLICATION_ID = "applicationId";

  public static final String BIKE_ID = "bikeId";

  public static final String CANCELLATION_POSSIBLE = "cancellationPossible";

  public static final String MONTHLY_NET_INCOME = "monthlyNetIncome";

  public static final String ORDER_ID = "orderId";

  private ProcessVariables() {
  }

  public static List<String> all() {
    return List.of(
        AGE,
        ALTERNATIVE_FOUND,
        APPLICATION_ID,
        BIKE_ID,
        CANCELLATION_POSSIBLE,
        MONTHLY_NET_INCOME,
        ORDER_ID);
  }
}
