// Generated by bpmn-to-code
package io.miragon.blueprint.adapter.process;

import java.util.List;

/**
 * Job worker task types used in {@code @JobWorker(type = ServiceTasks.X)} annotations.
 * Kept as {@code public static final String} because annotation arguments must be compile-time constants.
 */
public final class ServiceTasks {
  public static final String MIRAVELO_ACTIVATE_LEASING = "miravelo.activateLeasing";

  public static final String MIRAVELO_BOOK_COSTS = "miravelo.bookCosts";

  public static final String MIRAVELO_CANCEL_CONTRACT = "miravelo.cancelContract";

  public static final String MIRAVELO_CANCEL_POLICY = "miravelo.cancelPolicy";

  public static final String MIRAVELO_ISSUE_INSURANCE_POLICY = "miravelo.issueInsurancePolicy";

  public static final String MIRAVELO_ORDER_BIKE = "miravelo.orderBike";

  public static final String MIRAVELO_REQUEST_CANCELLATION = "miravelo.requestCancellation";

  public static final String MIRAVELO_SEND_CANCELLATION_CONFIRMATION = "miravelo.sendCancellationConfirmation";

  public static final String MIRAVELO_SEND_CONTRACT = "miravelo.sendContract";

  public static final String MIRAVELO_SEND_REJECTION = "miravelo.sendRejection";

  public static final String MIRAVELO_SEND_REMINDER_MAIL = "miravelo.sendReminderMail";

  private ServiceTasks() {
  }

  public static List<String> all() {
    return List.of(
        MIRAVELO_ACTIVATE_LEASING,
        MIRAVELO_BOOK_COSTS,
        MIRAVELO_CANCEL_CONTRACT,
        MIRAVELO_CANCEL_POLICY,
        MIRAVELO_ISSUE_INSURANCE_POLICY,
        MIRAVELO_ORDER_BIKE,
        MIRAVELO_REQUEST_CANCELLATION,
        MIRAVELO_SEND_CANCELLATION_CONFIRMATION,
        MIRAVELO_SEND_CONTRACT,
        MIRAVELO_SEND_REJECTION,
        MIRAVELO_SEND_REMINDER_MAIL);
  }
}
