// Generated by bpmn-to-code
package io.miragon.blueprint.adapter.process;

import io.miragon.bpmn.runtime.AbstractFlowNode;
import io.miragon.bpmn.runtime.BpmnElementType;
import io.miragon.bpmn.runtime.BpmnEngine;
import io.miragon.bpmn.runtime.BpmnEventType;
import io.miragon.bpmn.runtime.ElementId;
import io.miragon.bpmn.runtime.Event;
import io.miragon.bpmn.runtime.FlowNode;
import io.miragon.bpmn.runtime.HasJobType;
import io.miragon.bpmn.runtime.HasSuccessors;
import io.miragon.bpmn.runtime.HasVariables;
import io.miragon.bpmn.runtime.ProcessId;
import io.miragon.bpmn.runtime.SequenceFlows;
import io.miragon.bpmn.runtime.VariableDefinitions;
import io.miragon.bpmn.runtime.VariableName;
import java.util.List;

public final class CancelBikeOrderProcessApi {
  public static final ProcessId PROCESS_ID = new ProcessId("cancelBikeOrder");

  public static final BpmnEngine PROCESS_ENGINE = BpmnEngine.ZEEBE;

  private CancelBikeOrderProcessApi() {
  }

  /**
   * Typed navigation over the process flow: one nested class per BPMN element.
   */
  public static final class FlowNodes {
    private FlowNodes() {
    }

    public static EndEventOrderReversed endEventOrderReversed() {
      return EndEventOrderReversed.INSTANCE;
    }

    public static GatewayCancellationPossible gatewayCancellationPossible() {
      return GatewayCancellationPossible.INSTANCE;
    }

    public static GatewayJoin gatewayJoin() {
      return GatewayJoin.INSTANCE;
    }

    public static ServiceTaskBookCosts serviceTaskBookCosts() {
      return ServiceTaskBookCosts.INSTANCE;
    }

    public static ServiceTaskRequestCancellation serviceTaskRequestCancellation() {
      return ServiceTaskRequestCancellation.INSTANCE;
    }

    public static StartEventCancellationRequired startEventCancellationRequired() {
      return StartEventCancellationRequired.INSTANCE;
    }

    public static UserTaskClarifyReturn userTaskClarifyReturn() {
      return UserTaskClarifyReturn.INSTANCE;
    }

    public static List<FlowNode> all() {
      return List.of(
          EndEventOrderReversed.INSTANCE,
          GatewayCancellationPossible.INSTANCE,
          GatewayJoin.INSTANCE,
          ServiceTaskBookCosts.INSTANCE,
          ServiceTaskRequestCancellation.INSTANCE,
          StartEventCancellationRequired.INSTANCE,
          UserTaskClarifyReturn.INSTANCE);
    }

    public static final class EndEventOrderReversed extends AbstractFlowNode implements Event {
      public static final String ELEMENT_ID = "endEvent_orderReversed";

      public static final EndEventOrderReversed INSTANCE = new EndEventOrderReversed();

      private EndEventOrderReversed() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.END_EVENT, "Order reversed");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.NONE;
      }
    }

    public static final class GatewayCancellationPossible extends AbstractFlowNode implements HasSuccessors<GatewayCancellationPossible.Next> {
      public static final String ELEMENT_ID = "gateway_cancellationPossible";

      public static final GatewayCancellationPossible INSTANCE = new GatewayCancellationPossible();

      private GatewayCancellationPossible() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.EXCLUSIVE_GATEWAY, "Cancellation possible?");
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<GatewayJoin> gatewayJoin() {
          return SequenceFlows.single(new ElementId("flow_possibleToJoin"), "Yes", null, true, GatewayJoin.INSTANCE);
        }

        public SequenceFlows<UserTaskClarifyReturn> userTaskClarifyReturn() {
          return SequenceFlows.single(new ElementId("flow_notPossibleToClarifyReturn"), "No", "=cancellationPossible", false, UserTaskClarifyReturn.INSTANCE);
        }
      }
    }

    public static final class GatewayJoin extends AbstractFlowNode implements HasSuccessors<GatewayJoin.Next> {
      public static final String ELEMENT_ID = "gateway_join";

      public static final GatewayJoin INSTANCE = new GatewayJoin();

      private GatewayJoin() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.EXCLUSIVE_GATEWAY);
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<EndEventOrderReversed> endEventOrderReversed() {
          return SequenceFlows.single(new ElementId("flow_joinToReversed"), EndEventOrderReversed.INSTANCE);
        }
      }
    }

    public static final class ServiceTaskBookCosts extends AbstractFlowNode implements HasSuccessors<ServiceTaskBookCosts.Next>, HasJobType {
      public static final String ELEMENT_ID = "serviceTask_bookCosts";

      public static final ServiceTaskBookCosts INSTANCE = new ServiceTaskBookCosts();

      private ServiceTaskBookCosts() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.SERVICE_TASK, "Book costs");
      }

      @Override
      public String getJobType() {
        return ServiceTasks.MIRAVELO_BOOK_COSTS;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<GatewayJoin> gatewayJoin() {
          return SequenceFlows.single(new ElementId("flow_bookCostsToJoin"), GatewayJoin.INSTANCE);
        }
      }
    }

    public static final class ServiceTaskRequestCancellation extends AbstractFlowNode implements HasSuccessors<ServiceTaskRequestCancellation.Next>, HasJobType, HasVariables {
      public static final String ELEMENT_ID = "serviceTask_requestCancellation";

      public static final ServiceTaskRequestCancellation INSTANCE = new ServiceTaskRequestCancellation();

      private static final Variables VARIABLES = new Variables();

      private ServiceTaskRequestCancellation() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.SERVICE_TASK, "Request cancellation");
      }

      @Override
      public String getJobType() {
        return ServiceTasks.MIRAVELO_REQUEST_CANCELLATION;
      }

      @Override
      public Variables getVariables() {
        return VARIABLES;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Variables extends VariableDefinitions {
        public static final VariableName.Output CANCELLATION_POSSIBLE = new VariableName.Output(ProcessVariables.CANCELLATION_POSSIBLE);

        private Variables() {
        }

        @Override
        public List<VariableName> getAll() {
          return List.of(CANCELLATION_POSSIBLE);
        }
      }

      public static final class Next {
        public SequenceFlows<GatewayCancellationPossible> gatewayCancellationPossible() {
          return SequenceFlows.single(new ElementId("flow_requestToCancellationPossible"), GatewayCancellationPossible.INSTANCE);
        }
      }
    }

    public static final class StartEventCancellationRequired extends AbstractFlowNode implements HasSuccessors<StartEventCancellationRequired.Next>, Event, HasVariables {
      public static final String ELEMENT_ID = "startEvent_cancellationRequired";

      public static final StartEventCancellationRequired INSTANCE = new StartEventCancellationRequired();

      private static final Variables VARIABLES = new Variables();

      private StartEventCancellationRequired() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.START_EVENT, "Cancellation required");
      }

      @Override
      public BpmnEventType getEventType() {
        return BpmnEventType.NONE;
      }

      @Override
      public Variables getVariables() {
        return VARIABLES;
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Variables extends VariableDefinitions {
        public static final VariableName.Output BIKE_ID = new VariableName.Output(ProcessVariables.BIKE_ID);

        public static final VariableName.Output ORDER_ID = new VariableName.Output(ProcessVariables.ORDER_ID);

        private Variables() {
        }

        @Override
        public List<VariableName> getAll() {
          return List.of(BIKE_ID, ORDER_ID);
        }
      }

      public static final class Next {
        public SequenceFlows<ServiceTaskRequestCancellation> serviceTaskRequestCancellation() {
          return SequenceFlows.single(new ElementId("flow_startToRequestCancellation"), ServiceTaskRequestCancellation.INSTANCE);
        }
      }
    }

    public static final class UserTaskClarifyReturn extends AbstractFlowNode implements HasSuccessors<UserTaskClarifyReturn.Next> {
      public static final String ELEMENT_ID = "userTask_clarifyReturn";

      public static final UserTaskClarifyReturn INSTANCE = new UserTaskClarifyReturn();

      private UserTaskClarifyReturn() {
        super(new ElementId(ELEMENT_ID), BpmnElementType.USER_TASK, "Clarify return with supplier");
      }

      @Override
      public Next getNext() {
        return new Next();
      }

      public static final class Next {
        public SequenceFlows<ServiceTaskBookCosts> serviceTaskBookCosts() {
          return SequenceFlows.single(new ElementId("flow_clarifyReturnToBookCosts"), ServiceTaskBookCosts.INSTANCE);
        }
      }
    }
  }
}
