// Generated by bpmn-to-code
package io.miragon.blueprint.adapter.process;

import io.miragon.bpmn.runtime.BpmnErrorDefinition;
import java.util.List;

/**
 * BPMN error definitions with name and code, as thrown and caught by the processes.
 */
public final class Errors {
  public static final BpmnErrorDefinition APPLICATION_INVALID = new BpmnErrorDefinition("Application_Invalid", "applicationInvalid");

  private Errors() {
  }

  public static List<BpmnErrorDefinition> all() {
    return List.of(
        APPLICATION_INVALID);
  }
}
