// Generated by bpmn-to-code
package io.miragon.blueprint.adapter.process;

import io.miragon.bpmn.runtime.BpmnEscalationDefinition;
import java.util.List;

/**
 * BPMN escalation definitions with name and code, as thrown and caught by the processes.
 */
public final class Escalations {
  public static final BpmnEscalationDefinition CONTRACT_NOT_SIGNED = new BpmnEscalationDefinition("Contract_Not_Signed", "contractNotSigned");

  private Escalations() {
  }

  public static List<BpmnEscalationDefinition> all() {
    return List.of(
        CONTRACT_NOT_SIGNED);
  }
}
