// Generated by bpmn-to-code
@file:Suppress("unused")

package io.miragon.blueprint.adapter.process

import io.miragon.bpmn.runtime.BpmnEngine
import io.miragon.bpmn.runtime.BpmnError
import io.miragon.bpmn.runtime.BpmnEscalation
import io.miragon.bpmn.runtime.BpmnFlow
import io.miragon.bpmn.runtime.BpmnRelations
import io.miragon.bpmn.runtime.BpmnTimer
import io.miragon.bpmn.runtime.ElementId
import io.miragon.bpmn.runtime.MessageName
import io.miragon.bpmn.runtime.ProcessId
import io.miragon.bpmn.runtime.VariableName
import kotlin.String
import kotlin.Suppress

object BikeLeasingProcessProcessApi {
  val PROCESS_ID: ProcessId = ProcessId("bikeLeasingProcess")

  val PROCESS_ENGINE: BpmnEngine = BpmnEngine.ZEEBE

  /**
   * BPMN element ids as declared in the source model.
   * Typically used in process-level tests or when searching for tasks.
   * Worker runtime code rarely needs these.
   */
  object Elements {
    val BUSINESS_RULE_TASK_CHECK_CREDIT_RATING: ElementId =
        ElementId("businessRuleTask_checkCreditRating")

    val CALL_ACTIVITY_CANCEL_BIKE_ORDER: ElementId =
        ElementId("callActivity_cancelBikeOrder")

    val END_EVENT_APPLICATION_CANCELLED: ElementId =
        ElementId("endEvent_applicationCancelled")

    val END_EVENT_APPLICATION_REJECTED: ElementId = ElementId("endEvent_applicationRejected")

    val END_EVENT_CONTRACT_CANCELLED: ElementId = ElementId("endEvent_contractCancelled")

    val END_EVENT_CONTRACT_VALID: ElementId = ElementId("endEvent_contractValid")

    val END_EVENT_LEASING_ACTIVE: ElementId = ElementId("endEvent_leasingActive")

    val END_EVENT_NOT_SIGNED: ElementId = ElementId("endEvent_notSigned")

    val END_EVENT_PROSPECT_REMINDED: ElementId = ElementId("endEvent_prospectReminded")

    val EVENT_APPLICATION_INVALID: ElementId = ElementId("event_applicationInvalid")

    val EVENT_COMPENSATE_CONTRACT: ElementId = ElementId("event_compensateContract")

    val EVENT_COMPENSATE_INSURANCE: ElementId = ElementId("event_compensateInsurance")

    val EVENT_COMPENSATE_ORDER: ElementId = ElementId("event_compensateOrder")

    val EVENT_CONTRACT_NOT_SIGNED: ElementId = ElementId("event_contractNotSigned")

    val EVENT_CONTRACT_SIGNED: ElementId = ElementId("event_contractSigned")

    val EVENT_HANDOVER_REPORTED: ElementId = ElementId("event_handoverReported")

    val EVENT_REVERSE_APPLICATION: ElementId = ElementId("event_reverseApplication")

    val EVENT_SIGNATURE_DEADLINE: ElementId = ElementId("event_signatureDeadline")

    val EVENT_SIGNATURE_REMINDER: ElementId = ElementId("event_signatureReminder")

    val EVENT_TRIGGER_REVERSAL: ElementId = ElementId("event_triggerReversal")

    val EVENT_WITHDRAWAL_PERIOD_ELAPSED: ElementId =
        ElementId("event_withdrawalPeriodElapsed")

    val GATEWAY_ALTERNATIVE_FOUND: ElementId = ElementId("gateway_alternativeFound")

    val GATEWAY_AWAIT_SIGNATURE: ElementId = ElementId("gateway_awaitSignature")

    val GATEWAY_BIKE_AVAILABLE: ElementId = ElementId("gateway_bikeAvailable")

    val GATEWAY_BIKE_SOURCE_JOIN: ElementId = ElementId("gateway_bikeSourceJoin")

    val GATEWAY_FORK: ElementId = ElementId("gateway_fork")

    val GATEWAY_IS_SOLVENT: ElementId = ElementId("gateway_isSolvent")

    val GATEWAY_JOIN: ElementId = ElementId("gateway_join")

    val GATEWAY_REJECTION_JOIN: ElementId = ElementId("gateway_rejectionJoin")

    val SERVICE_TASK_ACTIVATE_LEASING: ElementId = ElementId("serviceTask_activateLeasing")

    val SERVICE_TASK_CANCEL_CONTRACT: ElementId = ElementId("serviceTask_cancelContract")

    val SERVICE_TASK_CANCEL_POLICY: ElementId = ElementId("serviceTask_cancelPolicy")

    val SERVICE_TASK_ISSUE_INSURANCE_POLICY: ElementId =
        ElementId("serviceTask_issueInsurancePolicy")

    val SERVICE_TASK_ORDER_BIKE: ElementId = ElementId("serviceTask_orderBike")

    val SERVICE_TASK_SEND_CANCELLATION_CONFIRMATION: ElementId =
        ElementId("serviceTask_sendCancellationConfirmation")

    val SERVICE_TASK_SEND_CONTRACT: ElementId = ElementId("serviceTask_sendContract")

    val SERVICE_TASK_SEND_REJECTION: ElementId = ElementId("serviceTask_sendRejection")

    val SERVICE_TASK_SEND_REMINDER_MAIL: ElementId =
        ElementId("serviceTask_sendReminderMail")

    val SERVICE_TASK_VALIDATE_APPLICATION: ElementId =
        ElementId("serviceTask_validateApplication")

    val START_EVENT_APPLICATION_WITHDRAWN: ElementId =
        ElementId("startEvent_applicationWithdrawn")

    val START_EVENT_CUSTOMER_ELIGIBLE: ElementId = ElementId("startEvent_customerEligible")

    val START_EVENT_LEASING_REQUEST_RECEIVED: ElementId =
        ElementId("startEvent_leasingRequestReceived")

    val SUB_PROCESS_APPLICATION_WITHDRAWN: ElementId =
        ElementId("subProcess_applicationWithdrawn")

    val SUB_PROCESS_CONCLUDE_CONTRACT: ElementId = ElementId("subProcess_concludeContract")

    val USER_TASK_CLARIFY_ALTERNATIVE: ElementId = ElementId("userTask_clarifyAlternative")
  }

  object CallActivities {
    val CALL_ACTIVITY_CANCEL_BIKE_ORDER: ProcessId = ProcessId("cancelBikeOrder")
  }

  /**
   * BPMN message names used to correlate messages to running process instances.
   */
  object Messages {
    val MIRAVELO_APPLICATION_WITHDRAWN: MessageName =
        MessageName("miravelo.applicationWithdrawn")

    val MIRAVELO_CONTRACT_SIGNED: MessageName = MessageName("miravelo.contractSigned")

    val MIRAVELO_HANDOVER_REPORTED: MessageName = MessageName("miravelo.handoverReported")

    val MIRAVELO_LEASING_REQUEST_RECEIVED: MessageName =
        MessageName("miravelo.leasingRequestReceived")
  }

  /**
   * Job worker task types used in `@JobWorker(type = ServiceTasks.X)` annotations.
   * Kept as `const val String` because annotation arguments must be compile-time constants.
   */
  object ServiceTasks {
    const val MIRAVELO_ACTIVATE_LEASING: String = "miravelo.activateLeasing"

    const val MIRAVELO_CANCEL_CONTRACT: String = "miravelo.cancelContract"

    const val MIRAVELO_CANCEL_POLICY: String = "miravelo.cancelPolicy"

    const val MIRAVELO_ISSUE_INSURANCE_POLICY: String = "miravelo.issueInsurancePolicy"

    const val MIRAVELO_ORDER_BIKE: String = "miravelo.orderBike"

    const val MIRAVELO_SEND_CANCELLATION_CONFIRMATION: String =
        "miravelo.sendCancellationConfirmation"

    const val MIRAVELO_SEND_CONTRACT: String = "miravelo.sendContract"

    const val MIRAVELO_SEND_REJECTION: String = "miravelo.sendRejection"

    const val MIRAVELO_SEND_REMINDER_MAIL: String = "miravelo.sendReminderMail"

    const val MIRAVELO_VALIDATE_APPLICATION: String = "miravelo.validateApplication"
  }

  object Timers {
    val EVENT_SIGNATURE_DEADLINE: BpmnTimer = BpmnTimer("Duration", "P14D")

    val EVENT_SIGNATURE_REMINDER: BpmnTimer = BpmnTimer("Duration", "P7D")

    val EVENT_WITHDRAWAL_PERIOD_ELAPSED: BpmnTimer = BpmnTimer("Duration", "P14D")
  }

  object Errors {
    val APPLICATION_INVALID: BpmnError =
        BpmnError("Application_Invalid", "applicationInvalid")
  }

  object Escalations {
    val CONTRACT_NOT_SIGNED: BpmnEscalation =
        BpmnEscalation("Contract_Not_Signed", "contractNotSigned")
  }

  object Compensations {
    val EVENT_COMPENSATE_CONTRACT: ElementId = ElementId("event_compensateContract")

    val EVENT_COMPENSATE_INSURANCE: ElementId = ElementId("event_compensateInsurance")

    val EVENT_COMPENSATE_ORDER: ElementId = ElementId("event_compensateOrder")

    val EVENT_REVERSE_APPLICATION: ElementId = ElementId("event_reverseApplication")

    val EVENT_TRIGGER_REVERSAL: ElementId = ElementId("event_triggerReversal")
  }

  /**
   * Process variables grouped by the BPMN element that declares them.
   * Direction is encoded in each variable's wrapper type: `VariableName.Input`, `VariableName.Output`, or `VariableName.InOut` when the variable is both read and written by the same element.
   * Consumer APIs that take a specific subtype (e.g. `fun setOutput(v: VariableName.Output)`) get compile-time direction enforcement.
   */
  object Variables {
    object CallActivityCancelBikeOrder {
      val APPLICATION_ID: VariableName.Input = VariableName.Input("applicationId")

      val BIKE_ID: VariableName.Input = VariableName.Input("bikeId")

      val ORDER_ID: VariableName.Input = VariableName.Input("orderId")
    }

    object ServiceTaskOrderBike {
      val BIKE_AVAILABLE: VariableName.Output = VariableName.Output("bikeAvailable")

      val ORDER_ID: VariableName.Output = VariableName.Output("orderId")
    }

    object StartEventLeasingRequestReceived {
      val AGE: VariableName.Output = VariableName.Output("age")

      val APPLICATION_ID: VariableName.Output = VariableName.Output("applicationId")

      val BIKE_ID: VariableName.Output = VariableName.Output("bikeId")

      val MONTHLY_NET_INCOME: VariableName.Output = VariableName.Output("monthlyNetIncome")
    }

    object UserTaskClarifyAlternative {
      val ALTERNATIVE_FOUND: VariableName.Output = VariableName.Output("alternativeFound")
    }
  }

  /**
   * Sequence flows between BPMN elements.
   * Mainly useful for process-model tooling, tests, and AI-agent consumers reasoning about the process shape.
   * Worker code typically does not need these.
   */
  object Flows {
    val FLOW_ACTIVATE_TO_ACTIVE: BpmnFlow = BpmnFlow(
          id = "flow_activateToActive",
          sourceRef = "serviceTask_activateLeasing",
          targetRef = "endEvent_leasingActive",
        )

    val FLOW_ALTERNATIVE_FOUND_TO_BIKE_SOURCE: BpmnFlow = BpmnFlow(
          id = "flow_alternativeFoundToBikeSource",
          name = "Yes",
          sourceRef = "gateway_alternativeFound",
          targetRef = "gateway_bikeSourceJoin",
          isDefault = true,
        )

    val FLOW_AWAIT_TO_CONTRACT_SIGNED: BpmnFlow = BpmnFlow(
          id = "flow_awaitToContractSigned",
          sourceRef = "gateway_awaitSignature",
          targetRef = "event_contractSigned",
        )

    val FLOW_AWAIT_TO_SIGNATURE_DEADLINE: BpmnFlow = BpmnFlow(
          id = "flow_awaitToSignatureDeadline",
          sourceRef = "gateway_awaitSignature",
          targetRef = "event_signatureDeadline",
        )

    val FLOW_BIKE_AVAILABLE_TO_JOIN: BpmnFlow = BpmnFlow(
          id = "flow_bikeAvailableToJoin",
          name = "Yes",
          sourceRef = "gateway_bikeAvailable",
          targetRef = "gateway_join",
          isDefault = true,
        )

    val FLOW_BIKE_SOURCE_TO_ORDER: BpmnFlow = BpmnFlow(
          id = "flow_bikeSourceToOrder",
          sourceRef = "gateway_bikeSourceJoin",
          targetRef = "serviceTask_orderBike",
        )

    val FLOW_BIKE_UNAVAILABLE_TO_CLARIFY: BpmnFlow = BpmnFlow(
          id = "flow_bikeUnavailableToClarify",
          name = "No",
          sourceRef = "gateway_bikeAvailable",
          targetRef = "userTask_clarifyAlternative",
          condition = "=not(bikeAvailable)",
        )

    val FLOW_CHECK_CREDIT_TO_SOLVENT: BpmnFlow = BpmnFlow(
          id = "flow_checkCreditToSolvent",
          sourceRef = "businessRuleTask_checkCreditRating",
          targetRef = "gateway_isSolvent",
        )

    val FLOW_CLARIFY_TO_ALTERNATIVE_FOUND: BpmnFlow = BpmnFlow(
          id = "flow_clarifyToAlternativeFound",
          sourceRef = "userTask_clarifyAlternative",
          targetRef = "gateway_alternativeFound",
        )

    val FLOW_CONCLUDE_TO_FORK: BpmnFlow = BpmnFlow(
          id = "flow_concludeToFork",
          sourceRef = "subProcess_concludeContract",
          targetRef = "gateway_fork",
        )

    val FLOW_CONFIRMATION_TO_CANCELLED: BpmnFlow = BpmnFlow(
          id = "flow_confirmationToCancelled",
          sourceRef = "serviceTask_sendCancellationConfirmation",
          targetRef = "endEvent_applicationCancelled",
        )

    val FLOW_CONTRACT_SIGNED_TO_VALID: BpmnFlow = BpmnFlow(
          id = "flow_contractSignedToValid",
          sourceRef = "event_contractSigned",
          targetRef = "endEvent_contractValid",
        )

    val FLOW_ELIGIBLE_TO_SEND_CONTRACT: BpmnFlow = BpmnFlow(
          id = "flow_eligibleToSendContract",
          sourceRef = "startEvent_customerEligible",
          targetRef = "serviceTask_sendContract",
        )

    val FLOW_FORK_TO_BIKE_SOURCE: BpmnFlow = BpmnFlow(
          id = "flow_forkToBikeSource",
          sourceRef = "gateway_fork",
          targetRef = "gateway_bikeSourceJoin",
        )

    val FLOW_FORK_TO_INSURANCE: BpmnFlow = BpmnFlow(
          id = "flow_forkToInsurance",
          sourceRef = "gateway_fork",
          targetRef = "serviceTask_issueInsurancePolicy",
        )

    val FLOW_HANDOVER_TO_WITHDRAWAL_PERIOD: BpmnFlow = BpmnFlow(
          id = "flow_handoverToWithdrawalPeriod",
          sourceRef = "event_handoverReported",
          targetRef = "event_withdrawalPeriodElapsed",
        )

    val FLOW_INSURANCE_TO_JOIN: BpmnFlow = BpmnFlow(
          id = "flow_insuranceToJoin",
          sourceRef = "serviceTask_issueInsurancePolicy",
          targetRef = "gateway_join",
        )

    val FLOW_INVALID_TO_REJECTION_JOIN: BpmnFlow = BpmnFlow(
          id = "flow_invalidToRejectionJoin",
          sourceRef = "event_applicationInvalid",
          targetRef = "gateway_rejectionJoin",
        )

    val FLOW_JOIN_TO_HANDOVER: BpmnFlow = BpmnFlow(
          id = "flow_joinToHandover",
          sourceRef = "gateway_join",
          targetRef = "event_handoverReported",
        )

    val FLOW_NO_ALTERNATIVE_TO_REVERSAL: BpmnFlow = BpmnFlow(
          id = "flow_noAlternativeToReversal",
          name = "No",
          sourceRef = "gateway_alternativeFound",
          targetRef = "event_triggerReversal",
          condition = "=not(alternativeFound)",
        )

    val FLOW_NOT_SIGNED_TO_REJECTION_JOIN: BpmnFlow = BpmnFlow(
          id = "flow_notSignedToRejectionJoin",
          sourceRef = "event_contractNotSigned",
          targetRef = "gateway_rejectionJoin",
        )

    val FLOW_NOT_SOLVENT_TO_REJECTION_JOIN: BpmnFlow = BpmnFlow(
          id = "flow_notSolventToRejectionJoin",
          name = "No",
          sourceRef = "gateway_isSolvent",
          targetRef = "gateway_rejectionJoin",
          condition = "=not(solvent)",
        )

    val FLOW_ORDER_TO_BIKE_AVAILABLE: BpmnFlow = BpmnFlow(
          id = "flow_orderToBikeAvailable",
          sourceRef = "serviceTask_orderBike",
          targetRef = "gateway_bikeAvailable",
        )

    val FLOW_RECEIVED_TO_VALIDATE: BpmnFlow = BpmnFlow(
          id = "flow_receivedToValidate",
          sourceRef = "startEvent_leasingRequestReceived",
          targetRef = "serviceTask_validateApplication",
        )

    val FLOW_REJECTION_JOINED: BpmnFlow = BpmnFlow(
          id = "flow_rejectionJoined",
          sourceRef = "gateway_rejectionJoin",
          targetRef = "serviceTask_sendRejection",
        )

    val FLOW_REMINDER_TO_SEND_MAIL: BpmnFlow = BpmnFlow(
          id = "flow_reminderToSendMail",
          sourceRef = "event_signatureReminder",
          targetRef = "serviceTask_sendReminderMail",
        )

    val FLOW_REVERSAL_TO_CONTRACT_CANCELLED: BpmnFlow = BpmnFlow(
          id = "flow_reversalToContractCancelled",
          sourceRef = "event_triggerReversal",
          targetRef = "endEvent_contractCancelled",
        )

    val FLOW_REVERSE_TO_SEND_CONFIRMATION: BpmnFlow = BpmnFlow(
          id = "flow_reverseToSendConfirmation",
          sourceRef = "event_reverseApplication",
          targetRef = "serviceTask_sendCancellationConfirmation",
        )

    val FLOW_SEND_CONTRACT_TO_AWAIT_SIGNATURE: BpmnFlow = BpmnFlow(
          id = "flow_sendContractToAwaitSignature",
          sourceRef = "serviceTask_sendContract",
          targetRef = "gateway_awaitSignature",
        )

    val FLOW_SEND_MAIL_TO_REMINDED: BpmnFlow = BpmnFlow(
          id = "flow_sendMailToReminded",
          sourceRef = "serviceTask_sendReminderMail",
          targetRef = "endEvent_prospectReminded",
        )

    val FLOW_SEND_REJECTION_TO_REJECTED: BpmnFlow = BpmnFlow(
          id = "flow_sendRejectionToRejected",
          sourceRef = "serviceTask_sendRejection",
          targetRef = "endEvent_applicationRejected",
        )

    val FLOW_SIGNATURE_DEADLINE_TO_NOT_SIGNED: BpmnFlow = BpmnFlow(
          id = "flow_signatureDeadlineToNotSigned",
          sourceRef = "event_signatureDeadline",
          targetRef = "endEvent_notSigned",
        )

    val FLOW_SOLVENT_TO_CONCLUDE_CONTRACT: BpmnFlow = BpmnFlow(
          id = "flow_solventToConcludeContract",
          sourceRef = "gateway_isSolvent",
          targetRef = "subProcess_concludeContract",
          isDefault = true,
        )

    val FLOW_VALIDATE_TO_CHECK_CREDIT: BpmnFlow = BpmnFlow(
          id = "flow_validateToCheckCredit",
          sourceRef = "serviceTask_validateApplication",
          targetRef = "businessRuleTask_checkCreditRating",
        )

    val FLOW_WITHDRAWAL_ELAPSED_TO_ACTIVE: BpmnFlow = BpmnFlow(
          id = "flow_withdrawalElapsedToActive",
          sourceRef = "event_withdrawalPeriodElapsed",
          targetRef = "serviceTask_activateLeasing",
        )

    val FLOW_WITHDRAWN_TO_REVERSE: BpmnFlow = BpmnFlow(
          id = "flow_withdrawnToReverse",
          sourceRef = "startEvent_applicationWithdrawn",
          targetRef = "event_reverseApplication",
        )
  }

  /**
   * Per-element graph metadata (previousElements / followingElements / parentId / boundary attachments).
   * Intended for tooling and tests, not worker runtime code.
   */
  object Relations {
    val BUSINESS_RULE_TASK_CHECK_CREDIT_RATING: BpmnRelations = BpmnRelations(
          name = "Check credit rating",
          previousElements = listOf("serviceTask_validateApplication"),
          followingElements = listOf("gateway_isSolvent"),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val CALL_ACTIVITY_CANCEL_BIKE_ORDER: BpmnRelations = BpmnRelations(
          name = "Cancel bike order",
          previousElements = emptyList(),
          followingElements = emptyList(),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val END_EVENT_APPLICATION_CANCELLED: BpmnRelations = BpmnRelations(
          name = "Leasing cancelled",
          previousElements = listOf("serviceTask_sendCancellationConfirmation"),
          followingElements = emptyList(),
          parentId = "subProcess_applicationWithdrawn",
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val END_EVENT_APPLICATION_REJECTED: BpmnRelations = BpmnRelations(
          name = "Application rejected",
          previousElements = listOf("serviceTask_sendRejection"),
          followingElements = emptyList(),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val END_EVENT_CONTRACT_CANCELLED: BpmnRelations = BpmnRelations(
          name = "Contract cancelled",
          previousElements = listOf("event_triggerReversal"),
          followingElements = emptyList(),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val END_EVENT_CONTRACT_VALID: BpmnRelations = BpmnRelations(
          name = "Contract valid",
          previousElements = listOf("event_contractSigned"),
          followingElements = emptyList(),
          parentId = "subProcess_concludeContract",
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val END_EVENT_LEASING_ACTIVE: BpmnRelations = BpmnRelations(
          name = "Leasing active",
          previousElements = listOf("serviceTask_activateLeasing"),
          followingElements = emptyList(),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val END_EVENT_NOT_SIGNED: BpmnRelations = BpmnRelations(
          name = "Not signed",
          previousElements = listOf("event_signatureDeadline"),
          followingElements = emptyList(),
          parentId = "subProcess_concludeContract",
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val END_EVENT_PROSPECT_REMINDED: BpmnRelations = BpmnRelations(
          name = "Prospect reminded",
          previousElements = listOf("serviceTask_sendReminderMail"),
          followingElements = emptyList(),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val EVENT_APPLICATION_INVALID: BpmnRelations = BpmnRelations(
          name = "Application invalid",
          previousElements = emptyList(),
          followingElements = listOf("gateway_rejectionJoin"),
          parentId = null,
          attachedToRef = "serviceTask_validateApplication",
          attachedElements = emptyList(),
        )

    val EVENT_COMPENSATE_CONTRACT: BpmnRelations = BpmnRelations(
          name = "Compensate contract",
          previousElements = emptyList(),
          followingElements = emptyList(),
          parentId = null,
          attachedToRef = "subProcess_concludeContract",
          attachedElements = emptyList(),
        )

    val EVENT_COMPENSATE_INSURANCE: BpmnRelations = BpmnRelations(
          name = "Compensate policy",
          previousElements = emptyList(),
          followingElements = emptyList(),
          parentId = null,
          attachedToRef = "serviceTask_issueInsurancePolicy",
          attachedElements = emptyList(),
        )

    val EVENT_COMPENSATE_ORDER: BpmnRelations = BpmnRelations(
          name = "Compensate order",
          previousElements = emptyList(),
          followingElements = emptyList(),
          parentId = null,
          attachedToRef = "serviceTask_orderBike",
          attachedElements = emptyList(),
        )

    val EVENT_CONTRACT_NOT_SIGNED: BpmnRelations = BpmnRelations(
          name = "Contract not signed",
          previousElements = emptyList(),
          followingElements = listOf("gateway_rejectionJoin"),
          parentId = null,
          attachedToRef = "subProcess_concludeContract",
          attachedElements = emptyList(),
        )

    val EVENT_CONTRACT_SIGNED: BpmnRelations = BpmnRelations(
          name = "Contract signed",
          previousElements = listOf("gateway_awaitSignature"),
          followingElements = listOf("endEvent_contractValid"),
          parentId = "subProcess_concludeContract",
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val EVENT_HANDOVER_REPORTED: BpmnRelations = BpmnRelations(
          name = "Handover reported",
          previousElements = listOf("gateway_join"),
          followingElements = listOf("event_withdrawalPeriodElapsed"),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val EVENT_REVERSE_APPLICATION: BpmnRelations = BpmnRelations(
          name = "Reverse application",
          previousElements = listOf("startEvent_applicationWithdrawn"),
          followingElements = listOf("serviceTask_sendCancellationConfirmation"),
          parentId = "subProcess_applicationWithdrawn",
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val EVENT_SIGNATURE_DEADLINE: BpmnRelations = BpmnRelations(
          name = "14 days",
          previousElements = listOf("gateway_awaitSignature"),
          followingElements = listOf("endEvent_notSigned"),
          parentId = "subProcess_concludeContract",
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val EVENT_SIGNATURE_REMINDER: BpmnRelations = BpmnRelations(
          name = "7 days",
          previousElements = emptyList(),
          followingElements = listOf("serviceTask_sendReminderMail"),
          parentId = null,
          attachedToRef = "subProcess_concludeContract",
          attachedElements = emptyList(),
        )

    val EVENT_TRIGGER_REVERSAL: BpmnRelations = BpmnRelations(
          name = "Trigger reversal",
          previousElements = listOf("gateway_alternativeFound"),
          followingElements = listOf("endEvent_contractCancelled"),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val EVENT_WITHDRAWAL_PERIOD_ELAPSED: BpmnRelations = BpmnRelations(
          name = "Await end of withdrawal period",
          previousElements = listOf("event_handoverReported"),
          followingElements = listOf("serviceTask_activateLeasing"),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val GATEWAY_ALTERNATIVE_FOUND: BpmnRelations = BpmnRelations(
          name = "Alternative found?",
          previousElements = listOf("userTask_clarifyAlternative"),
          followingElements = listOf("gateway_bikeSourceJoin", "event_triggerReversal"),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val GATEWAY_AWAIT_SIGNATURE: BpmnRelations = BpmnRelations(
          previousElements = listOf("serviceTask_sendContract"),
          followingElements = listOf("event_contractSigned", "event_signatureDeadline"),
          parentId = "subProcess_concludeContract",
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val GATEWAY_BIKE_AVAILABLE: BpmnRelations = BpmnRelations(
          name = "Bike available?",
          previousElements = listOf("serviceTask_orderBike"),
          followingElements = listOf("gateway_join", "userTask_clarifyAlternative"),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val GATEWAY_BIKE_SOURCE_JOIN: BpmnRelations = BpmnRelations(
          previousElements = listOf("gateway_fork", "gateway_alternativeFound"),
          followingElements = listOf("serviceTask_orderBike"),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val GATEWAY_FORK: BpmnRelations = BpmnRelations(
          previousElements = listOf("subProcess_concludeContract"),
          followingElements = listOf("gateway_bikeSourceJoin", "serviceTask_issueInsurancePolicy"),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val GATEWAY_IS_SOLVENT: BpmnRelations = BpmnRelations(
          name = "Solvent?",
          previousElements = listOf("businessRuleTask_checkCreditRating"),
          followingElements = listOf("subProcess_concludeContract", "gateway_rejectionJoin"),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val GATEWAY_JOIN: BpmnRelations = BpmnRelations(
          previousElements = listOf("serviceTask_issueInsurancePolicy", "gateway_bikeAvailable"),
          followingElements = listOf("event_handoverReported"),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val GATEWAY_REJECTION_JOIN: BpmnRelations = BpmnRelations(
          previousElements = listOf("event_applicationInvalid", "gateway_isSolvent", "event_contractNotSigned"),
          followingElements = listOf("serviceTask_sendRejection"),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val SERVICE_TASK_ACTIVATE_LEASING: BpmnRelations = BpmnRelations(
          name = "Activate leasing",
          previousElements = listOf("event_withdrawalPeriodElapsed"),
          followingElements = listOf("endEvent_leasingActive"),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val SERVICE_TASK_CANCEL_CONTRACT: BpmnRelations = BpmnRelations(
          name = "Cancel contract",
          previousElements = emptyList(),
          followingElements = emptyList(),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val SERVICE_TASK_CANCEL_POLICY: BpmnRelations = BpmnRelations(
          name = "Cancel policy",
          previousElements = emptyList(),
          followingElements = emptyList(),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val SERVICE_TASK_ISSUE_INSURANCE_POLICY: BpmnRelations = BpmnRelations(
          name = "Issue insurance policy",
          previousElements = listOf("gateway_fork"),
          followingElements = listOf("gateway_join"),
          parentId = null,
          attachedToRef = null,
          attachedElements = listOf("event_compensateInsurance"),
        )

    val SERVICE_TASK_ORDER_BIKE: BpmnRelations = BpmnRelations(
          name = "Order bike from dealer",
          previousElements = listOf("gateway_bikeSourceJoin"),
          followingElements = listOf("gateway_bikeAvailable"),
          parentId = null,
          attachedToRef = null,
          attachedElements = listOf("event_compensateOrder"),
        )

    val SERVICE_TASK_SEND_CANCELLATION_CONFIRMATION: BpmnRelations = BpmnRelations(
          name = "Send cancellation confirmation",
          previousElements = listOf("event_reverseApplication"),
          followingElements = listOf("endEvent_applicationCancelled"),
          parentId = "subProcess_applicationWithdrawn",
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val SERVICE_TASK_SEND_CONTRACT: BpmnRelations = BpmnRelations(
          name = "Send contract",
          previousElements = listOf("startEvent_customerEligible"),
          followingElements = listOf("gateway_awaitSignature"),
          parentId = "subProcess_concludeContract",
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val SERVICE_TASK_SEND_REJECTION: BpmnRelations = BpmnRelations(
          name = "Send rejection",
          previousElements = listOf("gateway_rejectionJoin"),
          followingElements = listOf("endEvent_applicationRejected"),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val SERVICE_TASK_SEND_REMINDER_MAIL: BpmnRelations = BpmnRelations(
          name = "Send reminder mail",
          previousElements = listOf("event_signatureReminder"),
          followingElements = listOf("endEvent_prospectReminded"),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val SERVICE_TASK_VALIDATE_APPLICATION: BpmnRelations = BpmnRelations(
          name = "Validate application",
          previousElements = listOf("startEvent_leasingRequestReceived"),
          followingElements = listOf("businessRuleTask_checkCreditRating"),
          parentId = null,
          attachedToRef = null,
          attachedElements = listOf("event_applicationInvalid"),
        )

    val START_EVENT_APPLICATION_WITHDRAWN: BpmnRelations = BpmnRelations(
          name = "Request withdrawn",
          previousElements = emptyList(),
          followingElements = listOf("event_reverseApplication"),
          parentId = "subProcess_applicationWithdrawn",
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val START_EVENT_CUSTOMER_ELIGIBLE: BpmnRelations = BpmnRelations(
          name = "Customer eligible",
          previousElements = emptyList(),
          followingElements = listOf("serviceTask_sendContract"),
          parentId = "subProcess_concludeContract",
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val START_EVENT_LEASING_REQUEST_RECEIVED: BpmnRelations = BpmnRelations(
          name = "Leasing request received",
          previousElements = emptyList(),
          followingElements = listOf("serviceTask_validateApplication"),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val SUB_PROCESS_APPLICATION_WITHDRAWN: BpmnRelations = BpmnRelations(
          name = "Application withdrawn",
          previousElements = emptyList(),
          followingElements = emptyList(),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val SUB_PROCESS_CONCLUDE_CONTRACT: BpmnRelations = BpmnRelations(
          name = "Conclude contract",
          previousElements = listOf("gateway_isSolvent"),
          followingElements = listOf("gateway_fork"),
          parentId = null,
          attachedToRef = null,
          attachedElements = listOf("event_compensateContract", "event_contractNotSigned", "event_signatureReminder"),
        )

    val USER_TASK_CLARIFY_ALTERNATIVE: BpmnRelations = BpmnRelations(
          name = "Clarify alternative with customer",
          previousElements = listOf("gateway_bikeAvailable"),
          followingElements = listOf("gateway_alternativeFound"),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
        )
  }
}
