// Generated by bpmn-to-code
@file:Suppress("unused")

package io.miragon.blueprint.adapter.process

import io.miragon.bpmn.runtime.AbstractFlowNode
import io.miragon.bpmn.runtime.BpmnElementType
import io.miragon.bpmn.runtime.BpmnEngine
import io.miragon.bpmn.runtime.BpmnEventType
import io.miragon.bpmn.runtime.ElementId
import io.miragon.bpmn.runtime.Event
import io.miragon.bpmn.runtime.FlowNode
import io.miragon.bpmn.runtime.HasJobType
import io.miragon.bpmn.runtime.HasSuccessors
import io.miragon.bpmn.runtime.HasVariables
import io.miragon.bpmn.runtime.ProcessId
import io.miragon.bpmn.runtime.RegisteredVariableDefinitions
import io.miragon.bpmn.runtime.SequenceFlows
import io.miragon.bpmn.runtime.VariableName
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

object CancelBikeOrderProcessApi {
  val PROCESS_ID: ProcessId = ProcessId("cancelBikeOrder")

  val PROCESS_ENGINE: BpmnEngine = BpmnEngine.ZEEBE

  /**
   * Typed navigation over the process flow: one nested object per BPMN element.
   */
  object FlowNodes {
    val all: List<FlowNode> = listOf(
      EndEventOrderReversed,
      GatewayCancellationPossible,
      GatewayJoin,
      ServiceTaskBookCosts,
      ServiceTaskRequestCancellation,
      StartEventCancellationRequired,
      UserTaskClarifyReturn,
    )

    object EndEventOrderReversed : AbstractFlowNode(
      id = ElementId(EndEventOrderReversed.ELEMENT_ID),
      elementType = BpmnElementType.END_EVENT,
      name = "Order reversed",
    ), Event {
      override val eventType: BpmnEventType = BpmnEventType.NONE

      const val ELEMENT_ID: String = "endEvent_orderReversed"
    }

    object GatewayCancellationPossible : AbstractFlowNode(
      id = ElementId(GatewayCancellationPossible.ELEMENT_ID),
      elementType = BpmnElementType.EXCLUSIVE_GATEWAY,
      name = "Cancellation possible?",
    ), HasSuccessors<GatewayCancellationPossible.Next> {
      const val ELEMENT_ID: String = "gateway_cancellationPossible"

      override val next: Next = Next

      object Next {
        val gatewayJoin: SequenceFlows<GatewayJoin>
          get() = SequenceFlows.single(
            flowId = ElementId("flow_possibleToJoin"),
            name = "Yes",
            isDefault = true,
            target = GatewayJoin,
          )

        val userTaskClarifyReturn: SequenceFlows<UserTaskClarifyReturn>
          get() = SequenceFlows.single(
            flowId = ElementId("flow_notPossibleToClarifyReturn"),
            name = "No",
            conditionExpression = "=cancellationPossible",
            target = UserTaskClarifyReturn,
          )
      }
    }

    object GatewayJoin : AbstractFlowNode(
      id = ElementId(GatewayJoin.ELEMENT_ID),
      elementType = BpmnElementType.EXCLUSIVE_GATEWAY,
    ), HasSuccessors<GatewayJoin.Next> {
      const val ELEMENT_ID: String = "gateway_join"

      override val next: Next = Next

      object Next {
        val endEventOrderReversed: SequenceFlows<EndEventOrderReversed>
          get() = SequenceFlows.single(
            flowId = ElementId("flow_joinToReversed"),
            target = EndEventOrderReversed,
          )
      }
    }

    object ServiceTaskBookCosts : AbstractFlowNode(
      id = ElementId(ServiceTaskBookCosts.ELEMENT_ID),
      elementType = BpmnElementType.SERVICE_TASK,
      name = "Book costs",
    ), HasSuccessors<ServiceTaskBookCosts.Next>, HasJobType {
      const val ELEMENT_ID: String = "serviceTask_bookCosts"

      override val jobType: String = ServiceTasks.MIRAVELO_BOOK_COSTS

      override val next: Next = Next

      object Next {
        val gatewayJoin: SequenceFlows<GatewayJoin>
          get() = SequenceFlows.single(
            flowId = ElementId("flow_bookCostsToJoin"),
            target = GatewayJoin,
          )
      }
    }

    object ServiceTaskRequestCancellation : AbstractFlowNode(
      id = ElementId(ServiceTaskRequestCancellation.ELEMENT_ID),
      elementType = BpmnElementType.SERVICE_TASK,
      name = "Request cancellation",
    ), HasSuccessors<ServiceTaskRequestCancellation.Next>, HasJobType, HasVariables {
      const val ELEMENT_ID: String = "serviceTask_requestCancellation"

      override val jobType: String = ServiceTasks.MIRAVELO_REQUEST_CANCELLATION

      override val variables: Variables = Variables

      override val next: Next = Next

      object Variables : RegisteredVariableDefinitions() {
        val CANCELLATION_POSSIBLE: VariableName.Output =
            output(ProcessVariables.CANCELLATION_POSSIBLE)
      }

      object Next {
        val gatewayCancellationPossible: SequenceFlows<GatewayCancellationPossible>
          get() = SequenceFlows.single(
            flowId = ElementId("flow_requestToCancellationPossible"),
            target = GatewayCancellationPossible,
          )
      }
    }

    object StartEventCancellationRequired : AbstractFlowNode(
      id = ElementId(StartEventCancellationRequired.ELEMENT_ID),
      elementType = BpmnElementType.START_EVENT,
      name = "Cancellation required",
    ), HasSuccessors<StartEventCancellationRequired.Next>, Event, HasVariables {
      override val eventType: BpmnEventType = BpmnEventType.NONE

      const val ELEMENT_ID: String = "startEvent_cancellationRequired"

      override val variables: Variables = Variables

      override val next: Next = Next

      object Variables : RegisteredVariableDefinitions() {
        val BIKE_ID: VariableName.Output = output(ProcessVariables.BIKE_ID)

        val ORDER_ID: VariableName.Output = output(ProcessVariables.ORDER_ID)
      }

      object Next {
        val serviceTaskRequestCancellation: SequenceFlows<ServiceTaskRequestCancellation>
          get() = SequenceFlows.single(
            flowId = ElementId("flow_startToRequestCancellation"),
            target = ServiceTaskRequestCancellation,
          )
      }
    }

    object UserTaskClarifyReturn : AbstractFlowNode(
      id = ElementId(UserTaskClarifyReturn.ELEMENT_ID),
      elementType = BpmnElementType.USER_TASK,
      name = "Clarify return with supplier",
    ), HasSuccessors<UserTaskClarifyReturn.Next> {
      const val ELEMENT_ID: String = "userTask_clarifyReturn"

      override val next: Next = Next

      object Next {
        val serviceTaskBookCosts: SequenceFlows<ServiceTaskBookCosts>
          get() = SequenceFlows.single(
            flowId = ElementId("flow_clarifyReturnToBookCosts"),
            target = ServiceTaskBookCosts,
          )
      }
    }
  }
}
