// Generated by bpmn-to-code
@file:Suppress("unused")

package io.miragon.blueprint.adapter.process

import io.miragon.bpmn.runtime.BpmnEngine
import io.miragon.bpmn.runtime.BpmnFlow
import io.miragon.bpmn.runtime.BpmnRelations
import io.miragon.bpmn.runtime.ElementId
import io.miragon.bpmn.runtime.ProcessId
import io.miragon.bpmn.runtime.VariableName
import kotlin.String
import kotlin.Suppress

object CancelBikeOrderProcessApi {
  val PROCESS_ID: ProcessId = ProcessId("cancelBikeOrder")

  val PROCESS_ENGINE: BpmnEngine = BpmnEngine.ZEEBE

  /**
   * BPMN element ids as declared in the source model.
   * Typically used in process-level tests or when searching for tasks.
   * Worker runtime code rarely needs these.
   */
  object Elements {
    val END_EVENT_ORDER_REVERSED: ElementId = ElementId("endEvent_orderReversed")

    val GATEWAY_CANCELLATION_POSSIBLE: ElementId = ElementId("gateway_cancellationPossible")

    val GATEWAY_JOIN: ElementId = ElementId("gateway_join")

    val SERVICE_TASK_BOOK_COSTS: ElementId = ElementId("serviceTask_bookCosts")

    val SERVICE_TASK_REQUEST_CANCELLATION: ElementId =
        ElementId("serviceTask_requestCancellation")

    val START_EVENT_CANCELLATION_REQUIRED: ElementId =
        ElementId("startEvent_cancellationRequired")

    val USER_TASK_CLARIFY_RETURN: ElementId = ElementId("userTask_clarifyReturn")
  }

  /**
   * Job worker task types used in `@JobWorker(type = ServiceTasks.X)` annotations.
   * Kept as `const val String` because annotation arguments must be compile-time constants.
   */
  object ServiceTasks {
    const val MIRAVELO_BOOK_COSTS: String = "miravelo.bookCosts"

    const val MIRAVELO_REQUEST_CANCELLATION: String = "miravelo.requestCancellation"
  }

  /**
   * Process variables grouped by the BPMN element that declares them.
   * Direction is encoded in each variable's wrapper type: `VariableName.Input`, `VariableName.Output`, or `VariableName.InOut` when the variable is both read and written by the same element.
   * Consumer APIs that take a specific subtype (e.g. `fun setOutput(v: VariableName.Output)`) get compile-time direction enforcement.
   */
  object Variables {
    object ServiceTaskRequestCancellation {
      val CANCELLATION_POSSIBLE: VariableName.Output =
          VariableName.Output("cancellationPossible")
    }

    object StartEventCancellationRequired {
      val BIKE_ID: VariableName.Output = VariableName.Output("bikeId")

      val ORDER_ID: VariableName.Output = VariableName.Output("orderId")
    }
  }

  /**
   * Sequence flows between BPMN elements.
   * Mainly useful for process-model tooling, tests, and AI-agent consumers reasoning about the process shape.
   * Worker code typically does not need these.
   */
  object Flows {
    val FLOW_BOOK_COSTS_TO_JOIN: BpmnFlow = BpmnFlow(
          id = "flow_bookCostsToJoin",
          sourceRef = "serviceTask_bookCosts",
          targetRef = "gateway_join",
        )

    val FLOW_CLARIFY_RETURN_TO_BOOK_COSTS: BpmnFlow = BpmnFlow(
          id = "flow_clarifyReturnToBookCosts",
          sourceRef = "userTask_clarifyReturn",
          targetRef = "serviceTask_bookCosts",
        )

    val FLOW_JOIN_TO_REVERSED: BpmnFlow = BpmnFlow(
          id = "flow_joinToReversed",
          sourceRef = "gateway_join",
          targetRef = "endEvent_orderReversed",
        )

    val FLOW_NOT_POSSIBLE_TO_CLARIFY_RETURN: BpmnFlow = BpmnFlow(
          id = "flow_notPossibleToClarifyReturn",
          name = "No",
          sourceRef = "gateway_cancellationPossible",
          targetRef = "userTask_clarifyReturn",
          condition = "=cancellationPossible",
        )

    val FLOW_POSSIBLE_TO_JOIN: BpmnFlow = BpmnFlow(
          id = "flow_possibleToJoin",
          name = "Yes",
          sourceRef = "gateway_cancellationPossible",
          targetRef = "gateway_join",
          isDefault = true,
        )

    val FLOW_REQUEST_TO_CANCELLATION_POSSIBLE: BpmnFlow = BpmnFlow(
          id = "flow_requestToCancellationPossible",
          sourceRef = "serviceTask_requestCancellation",
          targetRef = "gateway_cancellationPossible",
        )

    val FLOW_START_TO_REQUEST_CANCELLATION: BpmnFlow = BpmnFlow(
          id = "flow_startToRequestCancellation",
          sourceRef = "startEvent_cancellationRequired",
          targetRef = "serviceTask_requestCancellation",
        )
  }

  /**
   * Per-element graph metadata (previousElements / followingElements / parentId / boundary attachments).
   * Intended for tooling and tests, not worker runtime code.
   */
  object Relations {
    val END_EVENT_ORDER_REVERSED: BpmnRelations = BpmnRelations(
          name = "Order reversed",
          previousElements = listOf("gateway_join"),
          followingElements = emptyList(),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val GATEWAY_CANCELLATION_POSSIBLE: BpmnRelations = BpmnRelations(
          name = "Cancellation possible?",
          previousElements = listOf("serviceTask_requestCancellation"),
          followingElements = listOf("userTask_clarifyReturn", "gateway_join"),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val GATEWAY_JOIN: BpmnRelations = BpmnRelations(
          previousElements = listOf("gateway_cancellationPossible", "serviceTask_bookCosts"),
          followingElements = listOf("endEvent_orderReversed"),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val SERVICE_TASK_BOOK_COSTS: BpmnRelations = BpmnRelations(
          name = "Book costs",
          previousElements = listOf("userTask_clarifyReturn"),
          followingElements = listOf("gateway_join"),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val SERVICE_TASK_REQUEST_CANCELLATION: BpmnRelations = BpmnRelations(
          name = "Request cancellation",
          previousElements = listOf("startEvent_cancellationRequired"),
          followingElements = listOf("gateway_cancellationPossible"),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val START_EVENT_CANCELLATION_REQUIRED: BpmnRelations = BpmnRelations(
          name = "Cancellation required",
          previousElements = emptyList(),
          followingElements = listOf("serviceTask_requestCancellation"),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val USER_TASK_CLARIFY_RETURN: BpmnRelations = BpmnRelations(
          name = "Clarify return with supplier",
          previousElements = listOf("gateway_cancellationPossible"),
          followingElements = listOf("serviceTask_bookCosts"),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
        )
  }
}
