// Generated by bpmn-to-code
@file:Suppress("unused")

package io.miragon.blueprint.adapter.process

import io.miragon.bpmn.runtime.BpmnErrorDefinition
import kotlin.Suppress
import kotlin.collections.List

/**
 * BPMN error definitions with name and code, as thrown and caught by the processes.
 */
object Errors {
  val APPLICATION_INVALID: BpmnErrorDefinition = BpmnErrorDefinition(
    name = "Application_Invalid",
    code = "applicationInvalid",
  )

  val all: List<BpmnErrorDefinition> = listOf(
    APPLICATION_INVALID,
  )
}
